### ISSUE TITLE
issue with dplyr pipelines

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/DeclareDesign#10]
Using dplyr verbs step-by-step works as we know, but when you switch to do a multi-verb pipeline there seem to be problems. Recording a mwe here:

```
my_population <- declare_population(
  N = 30, my_var = rnorm(N), my_clusters = sample(1:3, N, replace = TRUE))

design <- declare_design(
  my_population,
  group_by(my_clusters),
  summarize(my_var_mean = mean(my_var)))
                  
# works!       
> draw_data(design)

# A tibble: 3 x 2
  my_clusters  my_var_mean
        <int>        <dbl>
1           1 -0.066540159
2           2 -0.046684309
3           3  0.004252965
```

But this seemingly identical code -- but for the use of pipelines instead of splitting up the steps -- does not:

```
design <- declare_design(
  my_population,
  group_by(my_clusters) %>% 
    summarize(my_var_mean = mean(my_var)))

> draw_data(design)
 Error in group_by(my_clusters) : object 'my_clusters' not found 
```

**Comment by acoppock** [comment]
We do say pass a list of functions... do we want to accommodate this functionality in the declare design function?

**Comment by graemeblair** [comment]
We're already not requiring functions though, i.e. 

```
declare_design(mutate(q = 5)) 
```

is not a function, but rather an expression. That expression works, but expression with pipelines don't. That seems a bit weird to me, but maybe you're right not damning.

**Comment by acoppock** [comment]
Not at my comp but does the pipeline work when enclosed in parentheses?

**Comment by graemeblair** [comment]
It does not, which I definitely find weird. Same error. Possible all this is fixed when we move to the new NSE; not sure.

**Comment by acoppock** [comment]
This was not fixed with the move to `rlang`.

**Comment by nfultz** [comment]
The reason why the above doesn't work (and never will) boils down operator precedence. Consider the AST of each
```

> ast(group_by(my_clusters))
\- ()
  \- `group_by
  \- `my_clusters 
> ast(summarize(my_var_mean = mean(my_var))
+ )
\- ()
  \- `summarize
  \- ()
    \- `mean
    \- `my_var 
```

each of these has a function call at the root, and the function takes a data argument.

Versus with the pipe:

```
> ast(group_by(my_clusters) %>% 
+     summarize(my_var_mean = mean(my_var)))
\- ()
  \- `%>%
  \- ()
    \- `group_by
    \- `my_clusters
  \- ()
    \- `summarize
    \- ()
      \- `mean
      \- `my_var
```

the Pipe is at the root, and pipes do not take data.

I would be open to 

```r
declare_design(
...,
. %>% group_by(my_clusters) %>% 
     summarize(my_var_mean = mean(my_var)))
)
```

which returns a `function(value)` - albeit without enough metadata to place into a DD pipeline.

**Comment by graemeblair** [comment]
I like that syntax with the ```. %>%```!
