### ISSUE TITLE
Update docs on what types of calls we will wrap

### ISSUE THREAD

**Issue by nfultz** [DeclareDesign/DeclareDesign#114]
Closing #10 - We need to be clear that only calls to a function with a data parameter will be autoboxed by `declare_design`

**Comment by graemeblair** [comment]
Just placeholdering the ```. %>%``` syntax here

**Comment by nfultz** [comment]
#150 added this warning:

```
        warning("Undeclared Step ", i, " function arguments are not exactly 'data'")
```


The magic dot makes a `function(value){}` and will trigger the warning.
