### ISSUE TITLE
nice output from print.diagnosis

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/DeclareDesign#117]
Macartan's suggested doing better in our output of the diagnosands data frame - I suggest we add a print.xtable method method for this (or if others have better solutions pls suggest)

Main desiderata: having diagnosand on one line and se(diagnosand) on next, regression table style; not looking like a jumble of words and numbers as we've always had it

**Comment by macartan** [comment]
print.xtable not working on diagnosis objects; can function below be generalized:

Current behavior:

```
> library(xtable)
> library(DeclareDesign)
> library(DesignLibrary)
> 
> design <- simple_two_arm_designer()
> diagnosis <- diagnose_design(design)
> print.xtable(diagnosis)
Error in rep(" ", nrow(x) + 2) : invalid 'times' argument
```

My ugly function:

```
cleanup_diagnosis <- function(diagnosis, digits = 2) { 
  
  D1  <- diagnosis[[2]]
  D   <- as.matrix(D1[,4:ncol(D1)])
  out <- matrix(NA, 2*nrow(D), ncol(D)/2+3)
  out[2*(1:nrow(D))-1, 4:ncol(out)] <- round(D[,2*(1:(ncol(D)/2))-1], digits)
  out[2*(1:nrow(D)),   4:ncol(out)] <- paste0("(", round(D[,2*(1:(ncol(D)/2))], digits), ")")

  out[2*(1:nrow(D))-1, 1:3] <- as.matrix(D1)[, 1:3]
  out[2*(1:nrow(D)), 1:3] <- " "
  colnames(out) <- colnames(D1[c(1:3, 3+2*(1:(ncol(D)/2))-1)])

  out
}  
kable(cleanup_diagnosis(diagnosis, digits = 2))
```


|estimator_label |coefficient |estimand_label |bias   |rmse   |power |coverage |mean_estimate |sd_estimate |type_s_rate |mean_estimand |
|:---------------|:-----------|:--------------|:------|:------|:-----|:--------|:-------------|:-----------|:-----------|:-------------|
|my_estimator    |Z           |ATE            |0.01   |0.2    |0.99  |0.94     |1.01          |0.23        |0           |1             |
|                |            |               |(0.01) |(0.01) |(0)   |(0.01)   |(0.01)        |(0.01)      |(0)         |(0.01)        |

**Comment by graemeblair** [comment]
addressed in https://github.com/DeclareDesign/DeclareDesign/pull/191
