### ISSUE TITLE
issue with setting N of lower levels when providing data

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/DeclareDesign#120]
The new solution recommended for drawing new levels with custom sample sizes included something like the following. Here, this doesn't work once you restart the session with the saved declared population, which it needs to for us to recommend this solution. 

```
my_data <- data.frame(noise = rnorm(50))

pop <- declare_population(
  data = my_data,
  
  new_level = add_level(
    N = sample(3:5, nrow(my_data), replace = TRUE)
  )
)

rm(my_data)

pop()
# Error in nrow(my_data): object 'my_data' not found
```

**Comment by nfultz** [comment]
I think this is fixed in the next version of fabricatr when N uses quosures
instead of substitute...

**Comment by graemeblair** [comment]
my bad; it works!
