### ISSUE TITLE
Bug in built-in custom function `difference_in_means_blocked`

### ISSUE THREAD

**Issue by amwilk** [DeclareDesign/DeclareDesign#120]
The function returns the mean of the control group minus the mean of the treatment group instead of the other way around.

**Comment by jaspercooper** [comment]
What, you're not interested in the inverse-ATE? ;)

**Comment by jaspercooper** [comment]
[Fixed](https://github.com/DeclareDesign/DeclareDesign/pull/121/commits/55434314758e8fd0ae87bb0518c4a490b9084e19)
