### ISSUE TITLE
diagnose_design with varying number of sims

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/DeclareDesign#121]
I propose the following syntax for `diagnose_design` to take advantage of the new function that allows you to run a subset of the design:

`diagnose_design(design = design, sims = 5)` works as usual

`diagnose_design(design = design, sims = c(5, 10, 1, 1))` simulates 5 in step 1 (i.e. the pop), 10 of the second step for each of the first step i.e. sampling, 1 each of the next steps per each of the 10 sampling steps.

Users could also specify if they prefer using names:

`diagnose_design(design = design, sims = c(my_pop = 5, my_sampling = 10, my_estimand = 1, my_sampling = 1))`

In addition to the usual columns in the simulations df, it will add a column sim_ID_stepname i.e. sim_ID_my_pop, one for each step. 

This would do the simulation, and the existing diagnosands would already work. Then users could write their own diagnosand function, that would for example do group_by(sim_ID_sampling) %>% summarize().

What do you think?

**Comment by graemeblair** [comment]
Let's impute 1's for the missing steps, or if vector isn't long enough we add 1's to the end

**Comment by nfultz** [comment]
Working for when `length(sims) == length(designs)`, moving error handling into its own ticket.
