### ISSUE TITLE
can we find a way to do completions for ... for the handlers

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/DeclareDesign#126]
that help you know what goes in ...

getting tooltips/suggestions for the default handlers

**Comment by jaspercooper** [comment]
Here's an example:

hit tab on Rstudio here `seq()` you get `... =`, hit tab here `seq(from = 1,)`, you get `to = ` etc.

**Comment by nfultz** [comment]
Please use https://github.com/DeclareDesign/completion.git and post any followups there.
