### ISSUE TITLE
issue installing on linux

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/DeclareDesign#127]
Here's a readout of an install error. @nfultz could you look at this today?

> install.packages("DeclareDesign", dependencies = TRUE, 
+                repos = c("http://R.declaredesign.org", "https://cloud.r-project.org"))
Installing package into ‘/home/user/R/x86_64-pc-linux-gnu-library/3.3’
(as ‘lib’ is unspecified)
trying URL 'http://R.declaredesign.org/src/contrib/DeclareDesign_0.2.0.tar.gz'
Content type 'application/gzip' length 177702 bytes (173 KB)
==================================================
downloaded 173 KB

* installing *source* package ‘DeclareDesign’ ...
** R
** inst
** preparing package for lazy loading
Error : object ‘add_level’ is not exported by 'namespace:fabricatr'
ERROR: lazy loading failed for package ‘DeclareDesign’
* removing ‘/home/chad/R/x86_64-pc-linux-gnu-library/3.3/DeclareDesign’
* restoring previous ‘/home/chad/R/x86_64-pc-linux-gnu-library/3.3/DeclareDesign’
Warning in install.packages :
  installation of package ‘DeclareDesign’ had non-zero exit status

The downloaded source packages are in
    ‘/tmp/RtmpLb84Fv/downloaded_packages’

**Comment by nfultz** [comment]
I can't repro - maybe try updating fabricatr first?
