### ISSUE TITLE
shortcut for coefficient_name if there is one row

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/DeclareDesign#130]
What do you all think about not requiring coefficient_name if there is a single row in the data.frame return from the estimator? 

The circumstance I have in mind is where you do a difference-in-means in a three-arm trial, and so properly done `difference_in_means` returns a single row but the rownames which we use to subset are labeled `ZT3` for example. It looks for Z and doesn't see it. Do we really need to scream in that case?

MWE:

```
> dat <- data.frame(y = runif(50), Z = sample(c("T1", "T2", "T3"), 50, replace =TRUE))
> my_est <- declare_estimator(y ~ Z, condition1 = "T2", condition2 = "T3")
> my_est(dat)
Error in data.frame(estimator_label = label, estimator_function(data,  : 
  arguments imply differing number of rows: 1, 0
```

Alternatively, @lukesonnet could make this return Z as the row name. I think this is because `difference_in_means` is using `lm_robust` in the background and `Z` is a factor.

**Comment by nfultz** [comment]
Try also coefficient_name = NULL to disable the filter - Z was always a
questionable default imho.

**Comment by nfultz** [comment]
fixed.
