### ISSUE TITLE
null diagnosands

### ISSUE THREAD

**Issue by acoppock** [DeclareDesign/DeclareDesign#146]
I have a case where my diagnosand is so custom, I can't use our framework.
I just need the sims, and I'll summarize my OWN way
I'd like to be able to do
```diagnose_design(design, diagnosands = NULL)```
or similar
pls

**Comment by acoppock** [comment]
e.g.,
```
test$simulations %>%
  group_by(sim_ID) %>%
  summarize(any_significant = any(p < alpha),
            num_significant = sum(p < alpha),
            all_significant = all(p < alpha)) %>%
  summarize(any_significant = mean(any_significant),
            num_significant = mean(num_significant),
            all_significant = mean(all_significant))

```

**Comment by acoppock** [comment]
or maybe this is a case for `simulate_design` ?

**Comment by nfultz** [comment]
Diagnosands *must* be a function - just plug in a dumb one -

diagnose_design(d, sims = 5, diagnosands=declare_diagnosands(foo=FALSE))



On Thu, Mar 15, 2018 at 2:49 PM, Alexander Coppock <notifications@github.com

**Comment by acoppock** [comment]
That's a shame. Can we add `simulate_design` that takes a design, returns a simulations_df?

**Comment by nfultz** [comment]
We have conduct_design for that?

On Thu, Mar 15, 2018 at 3:08 PM, Alexander Coppock <notifications@github.com

**Comment by nfultz** [comment]
Not sure what you are trying to accomplish.

**Comment by acoppock** [comment]
`conduct_design` is fine if we add a `sims` argument.  I would like to simulate a design but not run diagnosands on it, e.g., 

This is annoying
```
test <- diagnose_design(design, diagnosands = declare_diagnosands(foo=FALSE), sims = 100, bootstrap = FALSE)

test$simulations %>%
  group_by(sim_ID) %>%
  filter(coefficient != "(Intercept)") %>%
  summarize(any_significant = any(p < alpha),
            num_significant = sum(p < alpha),
            all_significant = all(p < alpha)) %>%
  summarize(any_significant = mean(any_significant),
            num_significant = mean(num_significant),
            all_significant = mean(all_significant))
```

this would be better

```
conduct_design(design, sims = 100) %>%
  group_by(sim_ID) %>%
  filter(coefficient != "(Intercept)") %>%
  summarize(any_significant = any(p < alpha),
            num_significant = sum(p < alpha),
            all_significant = all(p < alpha)) %>%
  summarize(any_significant = mean(any_significant),
            num_significant = mean(num_significant),
            all_significant = mean(all_significant))
```

**Comment by acoppock** [comment]
Also, the output of `conduct_design` appears to be a list of estimates_df and estimates_df.  What I'm looking for is a function that simulates a design sims times and returns the simulations df, i.e., exactly diagnosis$simulations_df

**Comment by nfultz** [comment]
ah your example didn't have any estimands in it.

**Comment by nfultz** [comment]
Also the main reason this doesn't work right now as a normal diagnosand function is that internally diagnosis assumes that "coefficient" is a diagnosand dimension, which prevents you from aggragting across different one - It makes more sense to expose finer grained control there than to split `simulate_design` away from diagnosis (a large change) and/or special case NULL (an ugly change).

**Comment by acoppock** [comment]
I'm happy with many solutions to this, including changing `conduct_design` behavior, adding `simulate_design` or NULLing / NAing out diagnosands in `diagnose_design`. up to you!
