### ISSUE TITLE
issue with redesign recognizing arguments

### ISSUE THREAD

**Issue by macartan** [DeclareDesign/DeclareDesign#158]
Trying to use redesign(design, parameter) where parameter is used in a handler; parameter seems not to be modified in handler

need to either make sure it gets picked up or describe in redesign documentation what gets updated and what not

[redesign.pdf](https://github.com/DeclareDesign/DeclareDesign/files/1886392/redesign.pdf)

**Comment by nfultz** [comment]
lexically scoped variables in handlers  can't be changed - that could break handlers (eg it could mask the `c()` function inside the handler or other core functions).  Only handler function parameters can be changed.
