### ISSUE TITLE
Extracting functions and other objects saved in a design

### ISSUE THREAD

**Issue by macartan** [DeclareDesign/DeclareDesign#159]
DO we have a method for extracting a list of objects saved in a design; eg functions, data etc. This is important for transparency so that users can figure out what the analysis code etc actually is:

Example:

```
#Open a design
load(url("http://www.columbia.edu/~mh2245/dark_design.Rdata"))

get_estimates(dark_design)
##   estimator_label      est estimand_label
## 1    my_estimator -1.02902      some_stat

#How is this estimation done? I can see the estimation function, sort of:
dark_design[[3]]
## declare_estimator(estimand = q, handler = tidy_estimator(my_private_estimator))

```
I can use it also.
```
df <- dark_design[[1]]()
est <- dark_design[[3]]
est(df)
##   estimator_label        est estimand_label
## 1    my_estimator -0.4337048      some_stat

```
But what is it? What is the analysis?

More generally. How can I get a list of the objects stored in the design?

[what_estimator.pdf](https://github.com/DeclareDesign/DeclareDesign/files/1891032/what_estimator.pdf)

**Comment by nfultz** [comment]
This is difficult / impossible in the general case, as each dependent function can have it's own environments (as in your example, where "my_private_estimator" is only present in a closure) and can be arbitrarily nested.

For a top level view of internals, we have methods for `str`:

```
> str(dark_design)
List of 3
 $ :design_step:	 declare_population(N = 6, Y = rnorm(N)) 
 $ :design_step:	 declare_estimand(some_stat = mean(Y)) 
 $ :design_step:	 declare_estimator(estimand = q, handler = tidy_estimator(my_private_estimator)) 
 - attr(*, "call")= language declare_design(pop, q, est)
 - attr(*, "class")= chr [1:2] "design" "d_par"

```


I really recommend using pryr / magrittr for this type of investigation.

to list objects in a step, use `ls` on the environment of the handler / dots:

```
> dark_design[[3]] %>% attr('handler') %>% environment %>% ls
[1] "estimator_function" "f"
```


To look at `my_private_estimator`, we know that tidy_estimator captures that as `estimator_function`, which we can pull out of the handler environment easily:

```
> dark_design[[3]] %>% attr('handler') %>% environment %>% extract2("estimator_function")
function(data){
  data.frame(est = with(data, mean(Y)-1))
}
```

Note that there is no guarantee that the estimand in step 2 is the same as `estimand = q` referenced in step 3, that would have to be manually verified.

```
> dark_design[[3]] %>% attr('dots') %>% extract2("estimand") 
<quosure>
  expr: ^q
  env:  0x555e1f51f970
> dark_design[[3]] %>% attr('dots') %>% extract2(1) %>% environment %>% extract2("q")
declare_estimand(some_stat = mean(Y))
```
This is only a weak check though, but should be sufficient for extracting the objects and eg fuzzing them.

**Comment by macartan** [comment]
Neal --- this is really useful. 

All: I am fairly worried that the nested environments make it very hard for others to see what the code is behind a design.  This pushes against the transparency goals of DD. I expect common uses will be to download a design and try to inspect the code; if key steps use functions or data or other objects in memory, be able to inspect those quickly also. Similarly one might expect others 
to want to extract the code and objects in such a way that various steps can be run (eg estimation) using code alone, not objects contained in the design environments.

Things that will help (largely making it easier for people to use the kind of approaches Neal describes):

## 1. Having a function to list the names of objects in any and all environments of a design. 

Something like:

```
object_names <- function(design, step=1) design[[step]] %>% attr('handler') %>% environment %>% ls
```
Ideally this would be able to go down a specified number of levels, or present an index of names with "addresses" for them. 

## 2. Having a function that extracts objects somewhere in the environment even if you are not sure where:

Something like:
```
get_object <- function(design, object_name, attri = "handler", step = "all"){
  if(step=="all"){
  lapply(design, function(j) {
    there <- as.vector(attr(j, attri) %>% environment %>% ls) %in% object_name
    if(sum(there)>0) get(object_name, envir = attr(j, 'handler') %>% environment)
    }) 
  }
  else get(object_name, envir = attr(design[[step]], 'handler') %>% environment)
  }

get_object(dark_design, "estimator_function", step = 3)

## function(data){
##   data.frame(est = with(data, mean(Y)-1))
## }
## <bytecode: 0x000000001c1eb180>
```
Again ideally search in lower level environments. Issues arise if multiple objects have same names; having the "address" of the found object would help.

## 3 Preserving names for objects.  
eg, as in Neal's  response we can figure out that we need `my_private_estimator`

```{r}
dark_design[[3]]
## declare_estimator(estimand = q, handler = tidy_estimator(my_private_estimator))
```

But the object in the environment that corresponds to my_private_estimator does not have this name

```object_names(dark_design, 3)
[1] "estimator_function" "f"
```
If it were called `my_private_estimator` then we could use a `get` type command as above.

```
get_object(dark_design, object_name = "my_private_estimator", step = "All")
```

## 4. Extract objects by type

If we have a function to extract things like this, would be good to be able to extract objects by type. 
```
get_object(dark_design, object_type = "estimator", step = "All")
```
This could, perhaps, help with `get_estimates(design, data)` which would be based on something like 
`ests <- get_object(dark_design, object_type = "estimator", step = 2)(data)`
where the step for the estimates is optionally specified in case there are several. Perhaps this is already implemented?

**Comment by nfultz** [comment]
For people doing that kind of stuff, they should just use the rstudio object explorer - click the magnifying glass next to the design in the environment window - be sure to click "show attributes" to expose the internal handler. 

![screenshot from 2018-04-10 15-28-09](https://user-images.githubusercontent.com/418638/38567043-b3aa2d38-3cd4-11e8-9474-061de3e8c97d.png)

This already provides a full listing of the object content as well as a search box, and you can click on each function to view it's source code.

**Comment by acoppock** [comment]
Neal, is there any help we can give to users here? something like an inspect(design) that would do a reasonably smart job of revealing what is going on?  it doesn't have to handle every case perfectly.

**Comment by nfultz** [comment]
what do you want that str(design) doesn't show?

**Comment by macartan** [comment]
I worry about people not being able to figure out the inputs to a design eg to recreate code outside of the DeclareDesign  package.   The fear is that DD will make designs less transparent for non expert users. 
e.g. as per last illustrations we may have:

```
> load(url("http://www.columbia.edu/~mh2245/dark_design.Rdata"))
> dark_design[[3]]
declare_estimator(estimand = q, handler = tidy_estimator(my_private_estimator))
```
Users will want to be able to figure out what my_private_estimator is, easily.  

Currently they cannot. If they click on the magnifying glass they have to go through: [[3]] > environment > FUN > environment > estimator_function and they still don't see an object called "my_private estimator".

Very useful would be something like:

```
> where_is(my_private_estimator)
address [eg set of paths like "[[3]] > environment / FUN / environment / estimator_function"
> my_private_estimator <- get(my_private_estimator, address)
```
or something like that. Find by name or type; get by name or type.  Of course objects with the same name may exist in multiple places, hence addresses might be needed as above.

Perhaps that already exists and we can instruct people on easy ways to use and access buried objects.

**Comment by nfultz** [comment]
In that case maybe tidyestimator function was a bad idea because it breaks
transparency - should we remove it? It is the only handler that would cause
this kind of renaming I think.

**Comment by acoppock** [comment]
My understanding is that the tidy_estimator wrapper solves a real problem for us (e.g., we need to make it easy for people to provide custom estimators).  So getting rid of it is probably not a good idea.  It comes with a cost, however, in transparency. Can we build some sort of work around that will expose the guts of the thing wrapped in tidy_estimator?
