### ISSUE TITLE
Add names to the steps of a design

### ISSUE THREAD

**Issue by macartan** [DeclareDesign/DeclareDesign#161]
Add names to the steps of a design

Elements of the design do not have names:

```
load(url("http://www.columbia.edu/~mh2245/dark_design.Rdata"))

names(dark_design)
## NULL

```
Though we can add them:

```
attr(dark_design, "call")
## declare_design(pop, q, est)
design_call <- attr(dark_design, "call")
names(dark_design) <- sapply(2:length(design_call), function(i) design_call[[i]])

names(dark_design)
## [1] "pop" "q"   "est"
dark_design$est
## declare_estimator(estimand = q, handler = tidy_estimator(my_private_estimator))

```
Would be useful to have these names added as a default; perhaps just using "Step_1" if the declaration does not include a name

e.g. declare_design(declare_population = 10)))

**Comment by nfultz** [comment]
Currently authors of designs can set names of steps if they want - and I would encourage them to do so - 

```
> d <- declare_design(my_population=pop)
> names(d)
[1] "my_population"
```

but what benefit does `design$Step_1` have over `design[[1]]` ?

**Comment by graemeblair** [comment]
closed by https://github.com/DeclareDesign/DeclareDesign/pull/199
