### ISSUE TITLE
draw_data appears to go through estimation steps

### ISSUE THREAD

**Issue by macartan** [DeclareDesign/DeclareDesign#167]
Following throws error in draw_data
```
pop <- declare_population(N = 10, Y = 1, X = 1, Z = 1)
estimand <- declare_estimand(S=mean(Y-X))
est <- declare_estimator(Y~X+Z, model = lm_robust, estimand = "S")
 
 design <- declare_design(pop, estimand, est)
 
> draw_data(design)
2 coefficients not defined because the design matrix is rank deficient
```

**Comment by graemeblair** [comment]
For both draw_data and get_estimates it runs the whole pipeline and returns the appropriate data frame. That's necessary for get_estimates but you're right not for draw_data. May not be straightforward to stop this but worth looking into for speed.

**Comment by nfultz** [comment]
This should be easy to fix
