### ISSUE TITLE
lm_robust blow up

### ISSUE THREAD

**Issue by macartan** [DeclareDesign/DeclareDesign#168]
Diagnostics blow up; slightly unusual data structure with collinearity risks, but still
see attached
[lm_robust_trouble_shoot.pdf](https://github.com/DeclareDesign/DeclareDesign/files/1907583/lm_robust_trouble_shoot.pdf)

**Comment by acoppock** [comment]
I think this is a case of "what happens when some sims have crazy or undefined answers".  

I don't know if there is a general solution to this; users would probably have to use the simulations data frame to run diagnostics conditional on the sim not blowing up.  (e.g., removing sim 1921)

**Comment by graemeblair** [comment]
I don't think the diagnosands are valid if we use an exclusion criteria like this

**Comment by macartan** [comment]
I share Graeme's worry, unless there were uncontestable notion that the
estimation didn't "work', but the dangers seem great
First q here is whether this is an issue with lm_robustt or a problem in
the data structure that lm_robust could identify and indicate

**Comment by lukesonnet** [comment]
I'll investigate re: estimatr tomorrow.

**Comment by lukesonnet** [comment]
This case is one where there is a linear dependence that the QR decomposition we use seems not to fail when it really should. You can use the following code to replicate a failing example:

```r
library(DeclareDesign)

n_groups <- 40
group_size <- 3
sd <- 1

# Model ----------------------------------------------------------------------
pop <- declare_population(N = n_groups*group_size,
                          G = rep(1:n_groups, each = group_size))
dgp <- function(i, Z, G) (sum(Z[G == G[i]])>0) + rnorm(1)*sd
# Inquiry --------------------------------------------------------------------
estimand <- declare_estimand(ATE = mean( sapply(1:length(G), function(i) {
  Z0 = rep(0, length(G))
  Z1 = (1:length(G))==i 
  dgp(i,Z1,G) - dgp(i, Z0, G)})
))
# Data
assignt <- declare_assignment()
reveal <- declare_reveal(handler=fabricate,
                         Y = sapply(1:N, function(i) dgp(i, Z, G)))
# Answer Strategy -------------------------------------------------------------
estimator <- declare_estimator(Y ~ Z, estimand = estimand, model = lm_robust)
# Design ----------------------------------------------------------------------
simple_spillover_design <- pop / assignt / reveal/ estimand / estimator

neighbor_treated <-
  declare_reveal(handler = fabricate,
                 neighbor = sapply(1:N, function(i) sum(Z[-i][G[-i]==G[i]])),
                 some_neighbor = 1 * (neighbor > 0))

solution_2 <-
  insert_step(simple_spillover_design, after = assignt, neighbor_treated)
solution_2 <-
  replace_step(
    solution_2,
    6,
    declare_estimator(Y ~ Z * some_neighbor,
                      estimand = estimand,
                      model = lm_robust)
  )


set.seed(434)
dat <- draw_data(solution_2)
lmro <- lm_robust(Y ~ Z * some_neighbor, data = dat)
summary(lm(Y ~ Z * some_neighbor, data = dat))

table(dat$some_neighbor, dat$Z)
```

This last line will show you that there are no control units with no neighbor.

I'm not sure why the QR decomposition is failing, but I'll look into it.

**Comment by graemeblair** [comment]
by default, diagnosands do not perform list-wise deletion so if there are any `NA` values in the simulations the diagnosand will be `NA`. this is the appropriate behavior. 

users can now see the sims df more easily so can find what is driving the NAs

(also some `lm_robust` behavior has been improved)
