### ISSUE TITLE
estimand label messiness

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/DeclareDesign#173]
from macartan:

correct behavior should be for explicit label to override implicit label

                    declare_estimand(2, label = "b")          -->  Label is b
                    declare_estimand(b = 2)                       --> Label is b
                    declare_estimand(a = 2, label = "b")    -->  Label is b

GB: think this rules is better than requiring label or removing it. need it in cases where you provide a custom handler, and nicer to have ATE = 2 syntax when you use the default.

see below cases

# accepts label for estimand
diagnose_design(declare_population(N = 4, Y = 1:4, Z = rep(0:1, 2)) /
                    declare_estimand(2, label = "b") /
                    declare_estimator( Y ~ Z, estimand = "b"),
                  sims = 2, bootstrap = 0)

# ignores label from estimand and takes it from the declaration instead
diagnose_design(declare_population(N = 4, Y = 1:4, Z = rep(0:1, 2)) /
                declare_estimand(a = 2, label = "b") /
                declare_estimand(b = 1, label = "a") /
                declare_estimator( Y ~ Z, estimand = "a"),
                sims = 2, bootstrap = 0)

# Confused even though only one estimand lablelled "a"
diagnose_design(declare_population(N = 4, Y = 1:4, Z = rep(0:1, 2)) /
                  declare_estimand(2, label = "b") /
                  declare_estimand(b = 1, label = "a") /
                  declare_estimator( Y ~ Z, estimand = "a"),
                sims = 2, bootstrap = 0)

# Confused
diagnose_design(declare_population(N = 4, Y = 1:4, Z = rep(0:1, 2)) /
                  declare_estimand(a = 2, label = "b") /
                  declare_estimator( Y ~ Z, estimand = "b"),
                sims = 2, bootstrap = 0)

**Comment by nfultz** [comment]
I'm fine with this - old behavior was legacy. However, please consider when there are multiple estimands in a step, such as:

```r
                declare_estimand(a1 = 1, a2=2, a3=3,  label = "b")    -->  Label is b
```

In this case, I think the label for the step should be "b" also, but this is fairly subtle

**Comment by macartan** [comment]
Interesting, are we saying:
in such cases "b" is the right label for the step - eg for use in
replace_step; but a1, a2 are the labels for the estimands, eg for
estimator(....., estimand = "a1").

**Comment by nfultz** [comment]
Right, I think things that operate on steps should use the step label
attribute, and things that need estimands should use estimand names.

**Comment by graemeblair** [comment]
closed by https://github.com/DeclareDesign/DeclareDesign/pull/199

tests made for each of the cases mentioned here
