### ISSUE TITLE
redesign needs a warning

### ISSUE THREAD

**Issue by macartan** [DeclareDesign/DeclareDesign#181]
should warn that attempts to change non existing parameters will not be noticed; eg

redesign(design, variance = 1)  (with some parameter, variance, written wrongly) will not change anything or issue a warning

ideal would be that this gets noticed by redesign

**Comment by nfultz** [comment]
This should be mentioned in the docs def.


  A runtime warning would be almost impossible bc of non standard
evaluation. Designs don't have any requirement or functionality for the
author to state which variables can change and which shouldn't.
