### ISSUE TITLE
Consider changing output of diagnose_design

### ISSUE THREAD

**Issue by acoppock** [DeclareDesign/DeclareDesign#183]
Right now we return a list with

$simulations_df
$diagnosands_df

we could add
$bootstrap_df

The summary functions could do what they want with them (possibly less error prone)?

**Comment by nfultz** [comment]
Why not just expose the bootstrapping functionality, and have people do `bootstrap(my_simulations)`

**Comment by jaspercooper** [comment]
Would love to have bootstraps out of `diagnose_design`. `bootstrap_diagnosis` could be user-facing and also live inside `cleanup_diagnosis`.

**Comment by macartan** [comment]
The branch I set up today does this i I think. It splits simulation from
diagnosis/bootstrapping and reports Sims and bootstraps in summary also,
easy as these are attributes on simulations_df so available.

A bit more to do and checks but comments on approach welcome

**Comment by macartan** [comment]
I made a `m_diagnosis` branch which reworks `diagnose_design`:

* It separates simulations and diagnosis/bootstrapping into two steps: `simulate_design` and `diagnose_design`
* Note before both the simulations and diagnosis were done in chunks when there were multiple designs; now the simulations is done in chunks but the diagnosis is done in one go with the design_ID added to the `group_by` list
* `diagnose_design` can take designs as before but can also take a `simulation_df`
* `diagnosands_df` now have three attributes:  sims,  bootstrap, and number of diagnosands
* The print summary now reports sims and bootstrap; with sims as a vector when it is a vector 
* `reshape_design` combines Alex's code and mine to take advantage of information in attributes 
* `reshape_design` changes diagnosand labels to make them prettier
* `reshape_design` no longer depends on `se(` but uses attributes of the diagnosand_df to figure out what's what
* `diagnose_design` now prints the reshaped summary and information on sims and bootstraps
* Most tests seem to be working *except* those related to attributes (I think)

* Illustrations attached

[diagnosis_memo.pdf](https://github.com/DeclareDesign/DeclareDesign/files/2037304/diagnosis_memo.pdf)

Next steps:

* Good if someone can look at tests and check out and merge in if OK
* Confirm that no  existing usages should be affected, other than having nicer printing of summary
* Note this replaces the reshape branch and the reshape function in DesignLibrary

**Comment by graemeblair** [comment]
https://github.com/DeclareDesign/DeclareDesign/pull/191 closes
