### ISSUE TITLE
get_estimates() get_estimands() on multiple designs

### ISSUE THREAD

**Issue by macartan** [DeclareDesign/DeclareDesign#185]
If we have multiple designs:
```
designs <- expand_design(
  simple_two_arm_designer,
  N = c(10:12))
```
`get_estimates(designs[[1]])` works  but this does not 

```
> get_estimates(designs)
Error in if (step_type %in% names(results)) { : 
  argument is of length zero
```
One can do essentially this using diagnose_design:

```
diagnose_design(designs, sims =1)[[1]]
```
But seems more natural to have get_estimates and get_estimands run on a list.

Note currently wanting this for a metaanalysis design where multiple designs are simultaneously declared and an estimator then takes an estimate from each. 

Aside -- there is a relation here to the diagnose_design(simulations_df...) request: currently diagnose design really does two distinct things that are useful separately (1) run the design one or many times and make a simulations_df (2) calculate diagnosands from a simulations_df;

A structure like this might make this more flexible:

```
run_design <- function(design, sims) {....}
diagnose_design <- function(simulations = NULL, design = NULL, diagnosands, sims = 500,...) {...
  if(is.null(simulations) & is.null(design)) stop("Must specify either a design or a simulations data frame")
  if(is.null(simulations)) simulations <- run_design(design, sims)
  ....
  } 
```

**Comment by nfultz** [comment]
You should use `sapply(designs, get_estimates)` - might warrant an example in ?get_estimates but from what you described, you would be better off writing custom diagnosands instead (which can aggregate across different designs iirc). Would rather not to make `get_estimates` generic when better alternatives for meta analysis are available.
