### ISSUE TITLE
expand_design has issues when only one design sought

### ISSUE THREAD

**Issue by macartan** [DeclareDesign/DeclareDesign#188]
This works:
```
designs <- expand_design(simple_two_arm_designer, N = 10:11)
```
This throws an error (in master branch):

```
designs <- expand_design(simple_two_arm_designer, N = 10)
 
 Error in match.call(expand.dots = FALSE) : 
  ... used in a situation where it does not exist 
```

**Comment by nfultz** [comment]
This looks like a bug in simple_two_arm_designer - there is a test here (that passed as of the last commit to master) that is very similar - https://github.com/DeclareDesign/DeclareDesign/blob/master/tests/testthat/test-quick-design.R#L26

**Comment by macartan** [comment]
Yes you are right; it doesn't happen if you comment the below

  #  attr(simple_two_arm_design, "code") <-
  #    construct_design_code(simple_two_arm_designer, match.call.defaults())

Is this a fix? It seems to work, but does it have issues?:

  expand_design <-
  function(template, expand = TRUE, ...) {

    design_args <- list(...)

    template_args_matrix <- if (expand)
      expand.grid(..., stringsAsFactors = FALSE)
    else
      cbind.data.frame(..., stringsAsFactors=FALSE)

    k <- nrow(template_args_matrix)
    if(k == 1) return( template(design_args) )

    by(template_args_matrix, 1:k, do.call, what=template, simplify = FALSE)

  }
  expand_design(simple_two_arm_designer, N = 5)

**Comment by macartan** [comment]
or better with do.call :

  expand_design <-
  function(template, expand = TRUE, ...) {

    template_args <- list(...)

    template_args_matrix <- if (expand)
      expand.grid(..., stringsAsFactors = FALSE)
    else
      cbind.data.frame(..., stringsAsFactors=FALSE)

    k <- nrow(template_args_matrix)
    if(k == 1) return(do.call(template, template_args)  )


    by(template_args_matrix, 1:k, do.call, what=template, simplify = FALSE)

  }

  a_expand_design <- expand_design(template = check_template, N = 50, prob
= .9)

**Comment by nfultz** [comment]
Thats an unnecessary work around for the fact that NSE in  simple_two_arm_designer is somewhat broken - we should fix it there - could be as simple as changing expand.dots in it's use of match.call.

**Comment by macartan** [comment]
GB can you look into this
Presumably this is relevant for all designers

**Comment by graemeblair** [comment]
Will look into
