### ISSUE TITLE
design labeling in diagnosis

### ISSUE THREAD

**Issue by macartan** [DeclareDesign/DeclareDesign#189]
If all designs have no labels, labels are generated; but not if  only *some* are:
```
designs = list(z = simple_two_arm_design,
               simple_two_arm_design,
               simple_two_arm_design)

> diagnose_design(designs = designs, sims = 3)$diagnosands[, 1:5]
  design_ID estimator_label coefficient estimand_label        bias
1         z    my_estimator           Z            ATE -0.05350339
2              my_estimator           Z            ATE  0.19150863
3              my_estimator           Z            ATE -0.19484499
```

Could create ambiguity,

Hopefully fixed in next go around but test would be useful

**Comment by nfultz** [comment]
Seems like this should just throw an error?

**Comment by graemeblair** [comment]
Let's add a design position as the design label, i.e. here labels would be c("z", "design_2", "design_3")

**Comment by graemeblair** [comment]
https://github.com/DeclareDesign/DeclareDesign/pull/191 closes
