### ISSUE TITLE
reveal_outcomes warning

### ISSUE THREAD

**Issue by acoppock** [DeclareDesign/DeclareDesign#19]
reveal_outcomes is an irritating necessity. 

We haven't figured out a way to infer which outcomes need to be revealed.  

It's not true in general that every potential outcomes object needs to have its outcomes revealed.

But probably the most common source of errors in calls to `declare_design` is forgetting to include a reveal_outcomes call.

As a band-aid, we are going to warn if 

there is at least one potential_outcomes function but no calls to reveal_outcomes.

**Comment by jaspercooper** [comment]
[Totally agree that this is going to come up a lot](https://github.com/DeclareDesign/DeclareDesign/issues/12#issuecomment-321288129).

I do think that the message should be conditional on an error occurring though: we may have people who have POs but for whatever reason they don't need to be revealed (i.e. it is done by their custom assignment function).

**Comment by graemeblair** [comment]
See #12
