### ISSUE TITLE
Error regarding many-to-many merge

### ISSUE THREAD

**Issue by macartan** [DeclareDesign/DeclareDesign#192]
In the help we decribe using coefficients = TRUE and naming estimands after coefficients. But it looks like we can just use the ordering of the estimators and map to  arbitrarily named estimands. eg:

```
U <- declare_population(N = 10, Y = rnorm(N), X = rep(0:1, 5))
Q <- declare_estimand("Control Mean" = 0, ATE = 1)
A <- declare_estimator(Y~X, model = lm_robust, 
                       estimand = c("Control Mean", "ATE"), 
                       label = 1:2, coefficients = TRUE)

diagnose_design(U / Q  / A)
```
works great.

```
> reshape_diagnosis(D)[,c(1:5, 12)]
  Estimator Label Coefficient Estimand Label   Bias   RMSE Mean Estimand
1               1 (Intercept)   Control Mean   0.02   0.45          0.00
3                                            (0.02) (0.01)        (0.00)
2               2           X            ATE  -1.04   1.21          1.00
4                                            (0.03) (0.02)        (0.00)
```
Two issues though:

1. Under this approach (with many estimators and estimands each in a single step) we have no way of saying that a particular estimator is to be connected with multiple estimands (the converse is easy)

2. When I link an estimand to multiple estimators I get this error, which seems unnecessary since the actual mapping should be easy (and is implemented correctly):

```
A <- declare_estimator(Y~X, model = lm_robust, 
                       estimand = c("ATE", "ATE"), 
                       label = 1:2, coefficients = TRUE)

D <- diagnose_design(U / Q  / A)

> reshape_diagnosis(D)[,c(1:5, 12)]
  Estimator Label Coefficient Estimand Label   Bias   RMSE Mean Estimand
1               1 (Intercept)            ATE  -1.01   1.12          1.00
3                                            (0.02) (0.02)        (0.00)
2               2           X            ATE  -1.00   1.19          1.00
4                                            (0.03) (0.03)        (0.00)
```

* Why the error?
* Is there a reason to promote the coefficient approach as described in help rather than this?

**Comment by acoppock** [comment]
This was a fun one to investigate.  Turns out that the error was correct!  The trouble was in the estimand declaration.  

This works as expected.  Basically, the warning occurred because there were no estimators matched to "control mean". changing Q fixes the problem.

```
U <- declare_population(N = 10, Y = rnorm(N), X = rep(0:1, 5))
Q <- declare_estimand(ATE = 1)
A <- declare_estimator(Y~X, model = lm_robust, 
                       estimand = c("ATE", "ATE"), label = c(1:2),
                       coefficients = TRUE)
D <- diagnose_design(U / Q  / A, sims = 5)
```

**Comment by macartan** [comment]
Good. Though one in general might want to be able to have an estimand to be
declared that is not actually estimated. (eg possibly will be estimated as
the design gets developed further)
