### ISSUE TITLE
easier declare_diagnosand

### ISSUE THREAD

**Issue by macartan** [DeclareDesign/DeclareDesign#194]
declare_diagnosand is a little hard to use; eg adding and subtracting from the default list is not easy.

The following behavior would be nice:

```
diagnosands = declare_diagnosands(select = c("bias", "RMSE"), 
                                  add = c(Mean_abs_error = "mean(abs(est - estimand))"))
diagnose_design(simple_two_arm_design, diagnosands = diagnosands, sims = 5)
```

```
Research design diagnosis, based on 5 simulations and 100 bootstrap draws.

 Estimator Label Coefficient Estimand Label Mean Abs Error   Bias   RMSE
    my_estimator           Z            ATE           0.14  -0.13   0.17
                                                    (0.04) (0.05) (0.04)
```
Below is a function that allows this. See also here: 
[declare_diagnosand.pdf](https://github.com/DeclareDesign/DeclareDesign/files/2065085/declare_diagnosand.pdf)

A couple of comments:

* This is probably not a good approach to implementation but this functionality is what we want I think. It does not have declaration and no handling of NULL stuff.  

* There is a question for us also whether diagnosands should be *declared* or not: they are not formally part of a design declaration, Rather they are suggested by the researcher and implemented after the design but readers could do different diagnoses of a design. 

* Do we have a method of selecting a researchers' preferred diagnoses as a default for declare design? This would make sense. The approach might be then to declare it and have it contained in the design, and then diagnose_design(design) first *looks* for a diagnosis declaration in the design and uses that instead of the default, if it is available. Then the researcher can be sure that when people do diagnose_design()  on their design they are looking at the relevant diagnosands. This may be particularly important if a design is really very different to the usual thing.

```
declare_diagnosands <- function(data, add_diagnosands = NULL, select_diagnosand = TRUE){

  diagnosands_set = c(
                    bias =  "mean(est - estimand)", 
                    RMSE = "sqrt(mean((est - estimand) ^ 2))",
                    power = "mean(p < .05)",
                    coverage = "mean(estimand <= ci_upper &
                                      estimand >= ci_lower)",
                    mean_estimate = "mean(est)",
                    sd_estimate = "sd(est)",
                    mean_se     = "mean(se)",
                    type_s_rate = "mean((sign(est) != sign(estimand))[ p < .05 ] )",
                    mean_estimand = "mean(estimand)")
  

  diagnosands_set <- diagnosands_set[select_diagnosand]

  diagnosands_set <- c(add_diagnosands, diagnosands_set)
  function(data){
  n <- length(diagnosands_set)
  data.frame(estimand_label = names(diagnosands_set),
             estimand       = sapply(1:n, function(j) 
                              with(data, eval(parse(text = diagnosands_set[j]))))
             )}
 }
```

**Comment by graemeblair** [comment]
I think we don't want it declared as part of a design; we are very clear it is not part of MIDA but rather a property of design. will work on selecting / adding diagnosands, which I agree could/should be easier.
