### ISSUE TITLE
Custom diagnosands appended but do not replace other diagnosands

### ISSUE THREAD

**Issue by jaspercooper** [DeclareDesign/DeclareDesign#222]
Example from documentation
```r
my_population <- declare_population(N = 500, noise = rnorm(N))
my_potential_outcomes <- declare_potential_outcomes(
  Y_Z_0 = noise, Y_Z_1 = noise +
  rnorm(N, mean = 2, sd = 2))
my_assignment <- declare_assignment()
my_estimand <- declare_estimand(ATE = mean(Y_Z_1 - Y_Z_0))
my_reveal <- declare_reveal()
my_estimator <- declare_estimator(Y ~ Z, estimand = my_estimand)
design <- my_population +
   my_potential_outcomes +
   my_estimand +
   my_assignment +
   my_reveal +
   my_estimator
my_diagnosand <- declare_diagnosands(absolute_error = mean(abs(est - estimand)))
diagnosis <- diagnose_design(design, diagnosands = my_diagnosand)
diagnosis
```
Returns diag table with *all* diagnosands, but should only return absolute_error. This is a problem for any design whose estimators don't return everything the default diagnosands need (I had this problem with process-tracing). 

Not immediately obvious to me where bug is arising.

**Comment by nfultz** [comment]
https://github.com/DeclareDesign/DeclareDesign/blob/master/R/declare_diagnosands.R#L21

keep.defaults seems not great but could be worse.

**Comment by jaspercooper** [comment]
Perfect, thanks. For those who stumble upon this in the future: 

```r
my_diagnosand <- declare_diagnosands(absolute_error = mean(abs(est - estimand)), keep_defaults = FALSE)
```

**Comment by nfultz** [comment]
Should probably surface that in ?declare_diagnosands if it isn't already
there.
