### ISSUE TITLE
diagnose_design check for declare has inappropriate error

### ISSUE THREAD

**Issue by lukesonnet** [DeclareDesign/DeclareDesign#228]
The error in these lines should be rewritten given that `declare_design` is deprecated. Also, if you pass `parallel = TRUE` this causes an error, but I guess that's because that's no longer an argument and it goes into the dots instead.

https://github.com/DeclareDesign/DeclareDesign/blob/a01ecce67b21acf89f491b39bd22a71b7fe4cd9b/R/diagnose_design.R#L107

**Comment by graemeblair** [comment]
Thanks, can you post example where this fails? I think the error is right to be there but should not say `declare_design`. Or am I misunderstanding? The error is meant to say if you don't have all design class objects (now created by +) then diagnose_design can't help you.

**Comment by nfultz** [comment]
see the futures package for enabling parallel.

**Comment by lukesonnet** [comment]
Sorry I came across this when I set `parallel = TRUE`, and realized shortly after opening it that it was deprecated. I decided to post the issue anyways because the error should not say `declare_design`, as you guessed, @graemeblair.

**Comment by graemeblair** [comment]
Thx will fix
