### ISSUE TITLE
Handle continuous POs

### ISSUE THREAD

**Issue by acoppock** [DeclareDesign/DeclareDesign#23]
We've had discussions re: continuous POs for a while; earlier versions of DD could handle them, the current version does not.

The issue is that 

`declare_potential_outcomes` returns a **function** that takes data and returns data with columns of potential outcomes appended.

With a continuous potential outcomes declaration, we can provide some columns, but not all, because there are infinitely many potential outcomes for each subject. The user can of course do something like:

```
declare_potential_outcomes(Y ~ X, assignment_variable_name = "X", condition_names = c(0, 0.25, 0.5, 0.75, 1)
```
 and we would sample 5 of the infinity of possible potential outcomes.

If there user does *not* specify any condition_names, then we really have no choice but to have declare_potential_outcomes return a function that takes data and returns the data unchanged, because there are literally no potential outcomes to return.

This is only a problem for the definition of estimands, because revealed outcomes can of course just use whatever X values actually occurred in order to run the function.

The change that is required for this functionality is a change to reveal_outcomes, which currenly only implements a generalized switching equation.  It will need to figure out somehow when it needs to run the actual PO function and when to do the switching equation.  This will clearly interface with the solution to #22

**Comment by nfultz** [comment]
MWE in PR #156

My thoughts:
  * PO need not be a "step" for these kinds of designs
  * estimand can be rewritten to use function directly, rather than Y_Z_1 columns
  * assignment needed a custom handler - randomizr in general not appropriate here - used fabricate
  * reveal needed a custom handler - used fabricate
