### ISSUE TITLE
simulate a design based on a custom design function rather than design object

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/DeclareDesign#230]
@macartan suggests allowing users to write their own design function that returns a run of the design (i.e. estimates and estimands)

This seems in line with our general philosophy of enter-and-exit-our-framework-at-will. Does not seem too hard to implement either. 

The function they write would have to return a list with two entries, estimates and estimands.

Others, thoughts?

**Comment by nfultz** [comment]
https://github.com/DeclareDesign/DeclareDesign/blob/a01ecce67b21acf89f491b39bd22a71b7fe4cd9b/R/design_helper_functions.R#L69

`run_design` is already a generic internally - if there is a non-design object you all would like to implement a method for, it probably would work so long as it returns a compatible list with estimates and estimands.
