### ISSUE TITLE
diagnosand labels 

### ISSUE THREAD

**Issue by macartan** [DeclareDesign/DeclareDesign#233]
Currently in `DeclareDesign:::default_diagnosands` we names cols as `estimand_label` and `estiamand`; Change to `diagnosand_label` and `diagnosand` unless there is a good reason for this

``` 
...
data.frame(estimand_label = c("bias",...),
                  estimand = c( bias , ...)}
```

**Comment by nfultz** [comment]
This was done to use the same code path in both diagnosands and estimands
(before defaults were factored out for better performance).  diagnosands
get pivoted anyway, so the names there are somewhat irrelevant.
