### ISSUE TITLE
More reshape details

### ISSUE THREAD

**Issue by macartan** [DeclareDesign/DeclareDesign#234]
In reshape_diagnosands: Currently the select columns code block is before the name cleaning and so select error message (ie use "bias", "estimand_label" etc) uses the wrong names; also select not being applied at all for cases with no bootstrapping; also cleaning code is there twice.

Order that was there before should be fine:

```
 if (is.null(diagnosis$bootstrap_replicates))  {
  out <- diagnosands_df
  } else {
  out <- reshaping
  }

# Then:
nice_names(out)
# Then:
select(out)
```

Other things:

1. parameters are still being capitalized
2. Too much repetition in se rows: we do not need repetition of parameter names or of N_sims (I also think we we do not need se (bootstrapped) unless there is some other possibility)
3. select should throw an error when only one column is selected

**Comment by graemeblair** [comment]
will fix

1. the capitalization is in a pull request posted yesterday following your issue
2. agreed 
3. why? can't we just do drop = FALSE?

**Comment by macartan** [comment]
also fine; was breaking when I used last but happy with this
