### ISSUE TITLE
plurals

### ISSUE THREAD

**Issue by macartan** [DeclareDesign/DeclareDesign#235]
declare_estimand and declare_estimator are in singular even though both can be used to declare multiple estiamands and estimators; perhaps keep these in plural?

**Comment by acoppock** [comment]
I agree it's annoying.  But I think the most common case will be one of each?  If it's plural, it will be inconsistent in the most common case?

**Comment by nfultz** [comment]
`population` and `assignment` are also singular. Vote for changing
`declare_potential_outcomes` to not have the final s, or a different
singular word.

**Comment by macartan** [comment]
I expect people will find declare_potential_outcome difficult as these are
almost always plural

I think either declare_assignment or declare_assignments works since
assignment can be thought of as over multiple things;

Sampling really needs to be singular. (Though my preference is to remove
declare_sampling altogether and instead have a drop option is
declare_assignment)

On the argument that one can be thought of as a special case of multiple
but not vice versa I think I'd still vote for
declare_population
declare_potential_outcomes
declare_assignment
declare_estimands
declare_estimators

Happy to leave as is if we cannot converge

**Comment by nfultz** [comment]
was going to suggest `declare_counterfactual` but I don't really love that either.

**Comment by graemeblair** [comment]
I think `declare_sampling` makes things easier to understand, only having assignment is too metaphysical. we're already asking a lot!

I don't have a strong pref on estimands and estimators. lean toward plural, in part because it highlights there can be more than one and the user has to tell us which coefficient (for example) is the estimator and of what. but hear @acoppock's arg that default will be one.

**Comment by acoppock** [comment]
I guess i vote for everything to stay the same. For me, the only change to consider is

`declare_estimands` and `declare_estimators`
vs.
`declare_estimand` and `declare_estimator`

it really is easy to declare plural estimands with a single declare_estimand/s step.  But it is *not* easy to declare multiple estimators in one step, e.g., one OLS and one GLM.  

So I think we should leave both singular.  (potential outcomes being plural is correct, imho)

**Comment by macartan** [comment]
In various applications with customized estimators multiple estimators get
defined as a block, a row per estimator

Similarly in coefficient = TRUE models, eg for k arm a set of coefficients
are simultaneously declared; are these different estimators? they come from
the same model for sure, but they are typically different estimates for
different estimands. Seems easy to me to think of this as a declaration of
estimators matching a declaration of estimands.

**Comment by graemeblair** [comment]
I am ok either way. Both seem likely to induce some confusion depending on what you plan to do with them (coefficients or not, multiple or single estimand).

**Comment by acoppock** [comment]
I agree with @macartan that sometimes the estimator is plural. But it's usually not! so I still vote singular. A (possibly bad?) compromise would be to have declare_estimators be an alias for declare_estimator

**Comment by macartan** [comment]
Sounds like pretty weak preferences. Alias basically resolves the problem
of having to remember so unless there are objections I think that is good.
If we there are objections then since you all have weak preferences I
prefer we do plural since that is more general, also consistent with
get_estimates, get_estimands etc.

**Comment by graemeblair** [comment]
Sounds good. Will implement the aliases now.
