### ISSUE TITLE
Error on misisng conditions

### ISSUE THREAD

**Issue by macartan** [DeclareDesign/DeclareDesign#236]
Error not very informative:
```
> Y  <- declare_potential_outcomes(Y ~ Z1 + Z2, assignment_variables = list("Z1", "Z2"))
Error in names(object) <- nm : 
  'names' attribute [2] must be the same length as the vector [1]
```
This is correct specification:

```
 Y  <- declare_potential_outcomes(Y ~ Z1 + Z2, conditions = list(Z1 = 0:1, Z2 = 0:1))
```

Assuming binary treatments  might be reasonable behavior when only variables are specified

**Comment by acoppock** [comment]
making that assumption would be consistent with how we deal with a single assignment variable... I'm OK with this change!

**Comment by nfultz** [comment]
Why not just get rid of `assignment_variables` (which is awful to type
anyway) and only offer conditions (perhaps make it also work with `c('Z1',
Z2')`)?

**Comment by macartan** [comment]
agree; naming vars and ranges in conditions seems efficient
