### ISSUE TITLE
more consistent docs

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/DeclareDesign#237]
Thread for making docs refer to design objects and other things more consistently. 

1. design objects "are created by linking together declared steps" or similar
2. use inheritparams in roxygen to achieve this for design objects and other things (any type of object we use >2 times)

**Comment by acoppock** [comment]
What is the *exact* syntax for inheriting the text for a single parameter?

**Comment by nfultz** [comment]
roxygen always inherits all params from a function, but you can make an unexported fn with a few params, then inherit from it -eg

https://github.com/DeclareDesign/DeclareDesign/blob/master/R/aaa.R#L189

https://github.com/DeclareDesign/DeclareDesign/blob/master/R/declare_estimator.R#L5
