### ISSUE TITLE
allowing functions and function calls to be in designs

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/DeclareDesign#239]
We've discussed allowing various types of non-DD objects into the design creation pipelines, including:
1) bare function names i.e. `pop + my_func`
2) function calls i.e. `pop + my_func(n = 50)` including dplyr function calls i.e. `pop + mutate(q = 5)`
3) dplyr pipelines i.e. `pop + . %>% group_by(my_group_var) %>% summarize(est = mean(y)`

I'd like all three to work in some way, if not with this syntax. 

Alex and I worked out case (a) in PR https://github.com/DeclareDesign/DeclareDesign/pull/238

That PR also includes a broken example for (2) that illustrates how we can't get it to work.

Here's what happens: 

```
> my_func <- function(data, my_n = 50){
+     data %>% sample_n(n = my_n)
+   }
> # errors before sending to our operator function
>   my_pop + my_func(my_n = 50)
 Show Traceback
 
 Rerun with Debug
 Error in eval(lhs, parent, parent) : 
  argument "data" is missing, with no default 
```

i.e. it tries to evaluate my_func(my_n = 50) before sending it to our + operator function.

Thoughts on doing (1)-(3) and also ideas on how to fix this problem appreciated! The error seems related to this set of comments by @nfultz : https://github.com/DeclareDesign/DeclareDesign/pull/216#issuecomment-395223138

**Comment by nfultz** [comment]
Note that #3 is a special case of #1. Instead do  `pop + (. %>% my_func(n =
50))` - if you really need to set n=50, make it the default, or have
my_func capture it and return a closure instead. You are probably not going
to prevent the evaluation of both operands becuase of `+`'s implementation
with both S4 group generics and S3 fallback.

**Comment by graemeblair** [comment]
Thanks @nfultz. Just so I'm clear, could you rewrite (1), (2) and (3) as you suggest they be called?

**Comment by graemeblair** [comment]
Update: I pushed a change that allows (1) and (3). You can do:

`pop + my_func`

`pop + . %>% mutate(my_var = 5)` or equivalently this works: `pop + (. %>% mutate(my_var = 5))`

So the only thing that doesn't work, which is a problem only when you want to change defaults, is `pop + my_func(n = 50)`
