### ISSUE TITLE
Citations

### ISSUE THREAD

**Issue by macartan** [DeclareDesign/DeclareDesign#250]
Think we want to have citations as a design attribute rather than as a step.

1. Can we make it easy to format the attribute so eg we have: 
`add_citation(design, title, author, year)` to replace `declare_citation(title, author)`

2. Alter `cite_design` so that it looks for bib information in attributes rather than in steps

**Comment by nfultz** [comment]
Why?

**Comment by acoppock** [comment]
I have always thought that citations are *not* part of the design, so it's weird to declare them!

If we make this change, we'd have syntax like:

```
des <- P + Y + S + A + I + E
des <- add_citation(des, "A title", "Some Authors", 2020)
```

Happy to make this change, just wanted to confirm syntax.

**Comment by macartan** [comment]
Think this is the right syntax; but what's with those super elegant short
step names?

re Neal's q -- yes, the idea is just formally we think of this as an
attribute of a design rather than a step in the design (though there is
something nice about the idea of getting the thing published as a final
step).

**Comment by nfultz** [comment]
But what if you have two citations? Meta analysis?

**Comment by nfultz** [comment]
Also note that add_citation can't work inline with plus signs because of operator precedence, eg:
```
> codetools::showTree(quo(A+B+C+D %>% cite(Neal)))
(~ (+ (+ (+ A B) C) (%>% D (cite Neal))))
```

**Comment by acoppock** [comment]
Hmm -- that seems like a bigger problem than just `add_citation`!

```
declare_population(N = 100) + declare_sampling(n = 100) %>% diagnose_design
 Show Traceback
 
 Rerun with Debug
 Error in check_design_class(designs) : 
  Please only send design objects or functions with no arguments to simulate_design.
```

though of course the following is OK
```
(declare_population(N = 100) + declare_sampling(n = 100)) %>% diagnose_design
```
I'm not sure under what circumstances you would want a single design to have multiple citations.

**Comment by nfultz** [comment]
Imagine I use:

```
my_estimator <- declare_estimator(handler=Fultz2018)
my_design <- regression_discontinuity_design(N=600, tau=.2) + my_estimator
```

And then go and publish a paper - Fultz 2018.  

Should I overwrite the existing citation with Fultz 2018? 

I would vote no because it seems bad for transparency. 

Also the functionality for multiple citations already works.

**Comment by acoppock** [comment]
I guess I'm more persuaded by the argument that citations are not part of the design, and I'm less concerned about allowing multiple citations. I've made the changes in this branch https://github.com/DeclareDesign/DeclareDesign/tree/add-citation. @macartan, happy to defer to you on how to resolve this dispute!

**Comment by nfultz** [comment]
recommend naming it set_citation since it sets/overwrites and doesn't add to a list.

**Comment by macartan** [comment]
@acoppock  I agree on attributes, thanks. 

I see Neal's point mattering especially for credit but think in documentatiin we can encourage people to give credit in the citation description field.

**Comment by macartan** [comment]
@macartan 

Let's do add rather than set 

Neal is right but think people will find add easier and unlikely to create confusion

**Comment by nfultz** [comment]
It will be confusing when something thinks it adds one and it instead overwrites the old one - this is a super common problem.

**Comment by nfultz** [comment]
eg there are several hundred questions like this on stackoverflow - https://stackoverflow.com/search?q=add+vs+set

we should follow standard conventions here.

**Comment by macartan** [comment]
Ok. Set!

**Comment by acoppock** [comment]
closed by https://github.com/DeclareDesign/DeclareDesign/pull/254, with set not add!
