### ISSUE TITLE
Ghosts in the machine

### ISSUE THREAD

**Issue by macartan** [DeclareDesign/DeclareDesign#257]
I got this odd behavior:
```
diagnose_design(designs = list(simple_two_arm_designer(N = 10), 
                               simple_two_arm_designer(N = 20), 
                               simple_two_arm_designer(N = 30)), 
                sims = 3)$diagnosands[, 1:3]

design_label estimand_label estimator_label
1     design_1            ATE    my_estimator
2     design_2            ATE    my_estimator
```

Which is incorrect because it yields only two designs. Then I removed objects in memory and got this:
  
```  
rm(list = ls())

diagnose_design(designs = list(simple_two_arm_designer(N = 10), 
                               simple_two_arm_designer(N = 20), 
                               simple_two_arm_designer(N = 30)), 
                sims = 3)$diagnosands[, 1:3]

design_label estimand_label estimator_label
1     design_1            ATE    my_estimator
2     design_2            ATE    my_estimator
3     design_3            ATE    my_estimator
```
which is correct. 

Can't understand that (and sorry I cannot replicate it) but I assume that something was in memory that was being used by diagnose_design to override something else. 

I think in the spirit of self contained designs we do not want design diagnosis accessing anything other than the design objects and any packages required of them.

Think this may be related to issues I have seen around saved designs not working when reloaded.

**Comment by graemeblair** [comment]
That is very weird, not sure what to do about it - I can't replicate either. 

I don't *think* diagnose_design is accessing anything but the designs you send it

**Comment by macartan** [comment]
Example where a design depends on an object in memory and fails after save / reloading

```
m <- 2
f <- function(x) m*x
u <- declare_population(N=2, X1 = 1)
s <- declare_step(fabricate, X1 = f(X1))
design <- u + s
draw_data(design)
##   ID X1 X2
## 1  1  2  2
## 2  2  2  2
```
Save, clear, reload:
```
save(design, file = "trouble.Rdata")
rm(list = ls())
load("trouble.Rdata")
draw_data(design)
## Error: Error in step 2 ():
##  Error in f(X1): object 'm' not found
```

**Comment by graemeblair** [comment]
Any advice here @nfultz ?
