### ISSUE TITLE
Clarify documentation on when redesign does not alter parameters

### ISSUE THREAD

**Issue by macartan** [DeclareDesign/DeclareDesign#264]
Do we have a concise statement of when a parameter will get modified by redesign? Should include in documentation for redesign warnings around when an argument does not get  changed. 

Consider the following:

```
m <- 2
f <- function(x) m*x
u <- declare_population(N=2, X1 = 1)
s <- declare_step(fabricate, X1 = f(X1), X2 = m)
design <- u + s

> draw_data(design)
  ID X1 X2
1  1  2  2
2  2  2  2

> draw_data(redesign(design, m = 3))
  ID X1 X2
1  1  2  3
2  2  2  3

```
Note that setting m = 3 in redesign changes X2 here but it does not change X1, because the role m plays for X1 is tucked inside the function f.

In contrast, below would be fine:

```
m <- 2
f <- function(x, m) m*x
u <- declare_population(N=2, X1 = 1)
s <- declare_step(fabricate, X1 = f(X1, m), X2 = m)
design <- u + s
```

**Comment by macartan** [comment]
@graemeblair Think we need to give some guidance on this for this release as there is a risk here of errors when using DD

**Comment by nfultz** [comment]
It doesn't recursively change any variables, only the environment of the
declared expression itself.


In your example


   global: f, m

  parent.env(f) = global

  X1 = quosure(f(1))
 X2 = quosure(m)


redesign changes parent.env(X1) and parent.env(X2) to *new environment*
with m = 3 which *overscopes global for each declared quosure*.

Note that after you run `draw_data(redesign(design, m = 3))`, look at m
again in global env
* still equals 2
* this is a feature, not a bug

**Comment by graemeblair** [comment]
In @macartan's first example, is that what you expect to happen though @nfultz?  I thought it should be:

```
> draw_data(redesign(design, m = 3))
  ID X1 X2
1  1  3  3
2  2  3  3
```

**Comment by macartan** [comment]
@graemeblair Neal's remarks clarify that the issue here is related to dd functions drawing on global environment which is not being altered by redeign. See below. 

Need a crisp set of warning / clarifications on this

Is there a way to prevent  dd functions using objects in the global environment in order to alert users to this kind of issue
 

```
> draw_data(redesign(design, m = 3))
  ID X1 X2
1  1  2  3
2  2  2  3
> 
> rm(m)
> 
> draw_data(redesign(design, m = 3))
 Error: Error in step 2 ():
	Error in f(X1): object 'm' not found 
```

**Comment by macartan** [comment]
Here is another instance of the sort of problem this can produce:

Makes me wonder again if there is any way we can stipulate what arguments can be accepted by redesign. Here ate is an argument of simple_two_arm_designer but it is not a modifiable argument of simple_two_arm_design because simple_two_arm_design simply uses treatment_mean <- control_mean + ate. One could imagine including an attribute of modifiable arguments that includes treatment_mean but not ate and send a message whenever someone tries to modify a non modifiable argument. 

One thing I like about this approach is that it makes it the business of design contributors to share what can be modified rather than suggesting that everything is modifiable. 
 


```
> library(DesignLibrary)
> 
> design1 <- simple_two_arm_designer(ate = 1)
> get_estimands(design1)
  estimand_label estimand
1            ATE        1
> 
> design2 <- expand_design(simple_two_arm_designer, ate = 2)
> get_estimands(design2)
  estimand_label estimand
1            ATE        2
> 
> 
> design3 <- redesign(design1, ate = 3)
> get_estimands(design2)
  estimand_label estimand
1            ATE        2
> 
> # oops
```

**Comment by nfultz** [comment]
> Makes me wonder again if there is any way we can stipulate what arguments can be accepted by redesign. 

Why would this be preferable to writing a function?

**Comment by macartan** [comment]
I imagine a situation where a user submits a design, eg to a funder or
peers, and indicates that various parameters can be changed quickly -- N,
ate etc using redesign. Listing modifiables in attributes makes this the
responsibility of people submitting designs.

Agree that submitting a designer would do the same thing but it seems more
straight forward to say "here is my design, feel free to explore
modifications to this design" than to say "here is a function that writes
my design and designs like it"

**Comment by nfultz** [comment]
So you are imagining a function like this:

```
x <- FUN(my_design, "N")
```

I think the value of x should be a `function(N)`, not a design object. Until the free variables are specified, it can't be diagnosed or simulated anyway. 

We should be encouraging our users, both those that write designs and those that run them, to use `expand_design` because it is unambiguous. `redesign` is a last resort.

**Comment by graemeblair** [comment]
documentation added in commit 7605013abbfca9861f139411b4d38b194252fffa
