### ISSUE TITLE
fan out interpretation

### ISSUE THREAD

**Issue by macartan** [DeclareDesign/DeclareDesign#268]
There may be a risk that users think that fan_n refers to step n, or at least are confused by how many fans there are and what they mean
May be helped by indicating what the fans are in the design summary or perhaps by naming them by end-step or by exporting check_sims
thoughts?

**Comment by acoppock** [comment]
propose:

step_1_sim step_2_sim

and that it prints all the step_*_sim columns regardless of whether the sim number varies.

**Comment by nfultz** [comment]
So just have duplicated columns in the output? :/

**Comment by macartan** [comment]
agree this is clear: step_1_sim step_2_sim

not too keen on printing all steps in output; output table quickly becomes
cluttered and think we should avoid uninformative content

**Comment by nfultz** [comment]
maybe for a sims = c(5, 1, 1, 1, 1, 2)

could be

step_1_sim step_2_to_5_sim step_6_sim

**Comment by acoppock** [comment]
am still in favor of all steps rather than a subset.  we never really print the steps, but it would be much clearer if the step number literally referred to the step number.

**Comment by macartan** [comment]
I prefer Neal's suggestion to having all steps as separate vars. Neal's
suggestion *is* explicit for all steps and avoids a possibly large number
of columns with no information (otherwise columns step_2_sim ---
step_5_sim) would all have 1s. it is also more interpretable since you can
read off that step_1_sim and step_6_sim vary but step_2_to_5_sim does not

> sims = c(5, 1, 1, 1, 1, 2) could be step_1_sim step_2_to_5_sim step_6_sim
