### ISSUE TITLE
set_diagnosands

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/DeclareDesign#273]
Aims: 
- enable `diagnose_design(my_designer())` to work even when default diagnosands won't, so setting diagnosands specific to the designer; and 
- make it easy for users to tell us what diagnosands are important for their design.

@macartan proposal:

1. set_diagnosands to add attribute 

2.  Diagnose design -- if no diagnosand stipulated, default is
A. Look for diagnosand attributes
B. If not, try default diagnosands

Need a default for diagnose_design also when diagnosands are not set for a design.

**Comment by graemeblair** [comment]
@macartan suggests the following syntax

diagnose_design <- function(design, diagnosands = NULL ...) {

if(is.null(diagnosands)) diagnosands <- attr(design, "diagnosands")
if(is.null(diagnosands)) diagnosands <- default_diagnosands

**Comment by graemeblair** [comment]
alternative:

diagnose_design <- function(design, diagnosands = default_diagnosands, override_design = FALSE) {

if(!override_set_diagnosands) diagnosands <- attr(design, "diagnosands")

**Comment by jaspercooper** [comment]
Just wanted to bump this. We need it for things like the Shiny app (i.e., randomized_response_designer() has no variance estimates so we really want only to report RMSE and bias for any diagnoses of the designs it produces).

**Comment by nfultz** [comment]
that looks fine but please use ifnull operator

diagnosands <- diagnosands %||% attr(design, "diagnosands") %||%
default_diagnosands

**Comment by graemeblair** [comment]
@nfultz @acoppock @jaspercooper do you have a view on the two syntaxes?

**Comment by graemeblair** [comment]
this will require more work; needs to handle different diagnosands for different designs which is not currently possible

I think diagnosands needs to take either a diagnosands object or a list of them

similarly, new `override_design` arg can be a vector

**Comment by macartan** [comment]
I find this harder to follow. Seems a bit more contorted. And if I want to
provide diagnosands this makes me first say what they are  and then
remember to say that yes I do really want to use them.

**Comment by acoppock** [comment]
I prefer macartan's proposal 

```diagnose_design <- function(design, diagnosands = NULL ...) {

if(is.null(diagnosands)) diagnosands <- attr(design, "diagnosands")
if(is.null(diagnosands)) diagnosands <- default_diagnosands
``` (with neal's suggested is null operator)

is there something I'm missing about what this is not preferable?

**Comment by jaspercooper** [comment]
Also like this (MH) syntax (although I do see the multiple designs problem, I guess this would have to be in a loop?).

Wondering whether we still want `diagnose_design(design,diagnosands = set_diagnosands(bias ...))`. I would vote yes, and that we move `keep_defaults` out of the default handler for `declare_diagnosands` and into `diagnose_design`. When `keep_defaults = TRUE` and design already has diagnosands set, you get the union.

**Comment by nfultz** [comment]
This ticket is for diagnose_designs if i understand correctly -

There should be no need to ever set an "override" flag there - if people provide dgs explicitly use those, ow if the design has some set use those, ow use the default.

that said , I think the declare_diagnosands handler could use another pass (which is a . seperate issue).

**Comment by graemeblair** [comment]
am ok with general consensus here; will implement and see what you think

@jaspercooper or @nfultz if you have suggestions on `declare_diagnosands` happy to address them in separate issue

**Comment by graemeblair** [comment]
what I've done in the PR so far is to implement 

`diagnosands <- diagnosands %||% attr(design, "diagnosands") %||% default_diagnosands` in a way that works for multiple designs (each can have its own diagnosands set via `set_diagnosands`)

there are two cases:
1) `diagnosands = NULL` - and you set diagnosands for some (or none) of the designs sent to diagnose_design
  - here, it uses the set diagnosands, except for the designs without them, where it uses `default_diagnosands`;
2) `diagnosands = your_diagnosands` - this uses your_diagnosands for all designs (overriding them).

I prevented you from sending a list of diagnosands, which would enable different diagnosands for different designs for now. is that a functionality we want?

**Comment by nfultz** [comment]
people that want different diagnosands on different designs can set them explicitly, eg
```
diagnose_design(
  set_diagnosands(design1, diagnosand1),
  set_diagnosands(design2, diagnosand2),
  set_diagnosands(design3, diagnosand3),
)
```

im not sure if we  correctly deal with the resulting output though.

**Comment by graemeblair** [comment]
ah, that's true. that's a clean way to do it. I'll confirm that works in a test

**Comment by macartan** [comment]
Thinking diagnosand attribute should be passed to simulations_df so that
user set attributes readily vailable if user passes simulations to diagnose
design

**Comment by nfultz** [comment]
I think it would be fine to also check a simulations_df data.frame for that attribute. AFAICT, set_diagnosands also works on data.frames.

**Comment by graemeblair** [comment]
sounds good
