### ISSUE TITLE
estimation errors

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/DeclareDesign#277]
We've discussed this before but it's pretty annoying for many tasks that diagnose_design doesn't do `na.rm = TRUE`. The diagnosands are not valid if we just drop them I think, but what if we do na.rm = TRUE, have a warning / message that says "Some estimation resulted in errors. The diagnosands reflect the properties of the design conditional on not resulting in an error." And printing the proportion errored.

**Comment by acoppock** [comment]
I like this proposal.  is it true that errors cause NAs in the sims dataframe?

**Comment by macartan** [comment]
For many designs there out to be no missing data and the alert to missing
is informative. The warning may be enough, am happy with that.
An alternatives  might be to have a na.rm = FALSE argument so people can
override easily when they want to
It would also be useful if the sim count counted all the non missing
observation used in the calculation of the diagnosand. That might be the
case anyhow but that could be very informative -- you run 1000 sims and you
get a result based on just 10.

**Comment by nfultz** [comment]
> The diagnosands are not valid if we just drop them I think

What's the issue with just propagating the NAs and not dropping them? If an
estimator or estimand is NA, shouldn't the diagnosand be NA also? - and if
people want to change the behavior, they can always provide a different
diagnosand.

**Comment by acoppock** [comment]
Yes, I think that neal and macartan's comments can be accomodated with a na.rm argument to `diagnose_design`, set by default to... FALSE?

**Comment by graemeblair** [comment]
can't easily do an `na.rm` argument in `diagnose_design` - the `na.rm` would actually be in the diagnosand function itself. would have to edit the arguments to the diagnosands (which among other things would violate the fact that we declared the diagnosand function. but this does seem like what we want to do!

**Comment by nfultz** [comment]
you should add na.rm to declare_diagnosands, not diagnose_design.

**Comment by acoppock** [comment]
just recording here a thought that it would be useful to save estimation errors.

**Comment by macartan** [comment]
Here is an example where errors (due to too much missing data) produce NAs in a spotty way in diagnosis

```
library(DesignLibrary)
set.seed(1)
diagnose_design(two_arm_attrition_designer(b_R = 0, rho = .8), sims = 2)
diagnose_design(two_arm_attrition_designer(b_R = 0, rho = .8), sims = 100)
```


```
Design Label     Estimand Label Estimator Label Coefficient N Sims   Bias   RMSE  Power Coverage Mean Estimate SD Estimate Mean Se
     design_1           ATE on R        DIM on R           Z    100   0.00   0.10   0.03     0.97          0.00        0.10    0.10
                                                                    (0.01) (0.01) (0.02)   (0.02)        (0.01)      (0.01)  (0.00)
     design_1           ATE on Y        DIM on Y           Z    100  -0.00   0.08   0.97     0.97          0.34        0.09    0.09
                                                                    (0.01) (0.00) (0.02)   (0.02)        (0.01)      (0.01)  (0.00)
     design_1           ATE on Y    DIM on Y_obs           Z    100  -0.15   0.17     NA       NA          0.19        0.09    0.08
                                                                    (0.01) (0.01)     NA       NA        (0.01)      (0.01)  (0.00)
     design_1 ATE on Y (Given R)        DIM on Y           Z    100   0.15   0.18   0.97     0.54          0.34        0.09    0.09
                                                                    (0.01) (0.01) (0.02)   (0.05)        (0.01)      (0.01)  (0.00)
     design_1 ATE on Y (Given R)    DIM on Y_obs           Z    100  -0.00   0.06     NA       NA          0.19        0.09    0.08
                                                                    (0.01) (0.01)     NA       NA        (0.01)      (0.01)  (0.00)
```

Here mean_se is here but power is not; could reduce to non NA cases and make sims informative about cases used
