### ISSUE TITLE
does confint need to be a data.frame in estimator_handler?

### ISSUE THREAD

**Issue by jaspercooper** [DeclareDesign/DeclareDesign#278]
Right now `estimator_handler` is choking on a `confint()` object returned by `systemfit` because it is a matrix classed as `confint.systemfit` and therefore can't be coerced to a data.frame. Seems a shame because really we are quite close to this working. It makes me wonder whether other estimators might exhibit this issue
MWE:
```r
library(DeclareDesign)
library(systemfit)
library(DesignLibrary)
data <- draw_data(crossover_designer())
sur_fit <- systemfit(
			formula = list(YA ~ A, YB ~ B),
			method = "SUR",
			data = data)
SUR <- declare_estimator(
  formula = list(YA ~ A, YB ~ B),
  model = systemfit,
  method = "SUR",
  coefficients = "eq1_A",
  label = "SUR"
)
# Looks great:
as.matrix(confint(sur_fit))
# Awesome, we can pull the confint:
confint(sur_fit)["eq1_A",]
# Womp:
SUR(data)
as.data.frame(confint(sur_fit))
```

**Comment by jaspercooper** [comment]
(Sorry had to update code)

**Comment by nfultz** [comment]
What S3 method for as.data.frame is getting called instead? Is the issue that systemfit is returning an S4 object?

**Comment by graemeblair** [comment]
it seems to be that confint(sur_fit) returns a matrix that was custom classed as a `confint.systemfit` object and there's no `as.data.frame` method for it.

**Comment by nfultz** [comment]
You should email the author of that package, it should take them like 5 minutes to add it.

**Comment by graemeblair** [comment]
@jaspercooper do you want to do this?

**Comment by acoppock** [comment]
propose we write a small function:

check_model(fit)

That tells you if it's gonna be compatible.

**Comment by jaspercooper** [comment]
Happy to write to them, but also was anticipating this coming up in other instances and was thinking about whether we have estimator_handler work in a more class-agnostic way. But looking at fit2tidy I can see how it's quite important that these objects be easily turned into data.frames

**Comment by acoppock** [comment]
occurs to me that fit2tidy is just a poor man's `broom::tidy`.  The dependencies for `broom` are just immense, tho, so we can't use it.

**Comment by nfultz** [comment]
Yeah, we already had that discussion in estimatr.

**Comment by acoppock** [comment]
So I went through some of the models that broom supports and made a test for us.  there's lots we don't support and probably can't without depending on broom.  See tests here: https://github.com/DeclareDesign/DeclareDesign/blob/model-tests/tests/testthat/test-models.R

**Comment by acoppock** [comment]
We've done a soft depend on broom for anything that broom handles that isn't an estimatr function or lm / glm.  For systemfit, since it doesn't work with broom (short of @jaspercooper doing a PR for it for broom), that'll need to be a custom estimation function.
