### ISSUE TITLE
confirm that estimand/estimator labels work correctly and in all combinations

### ISSUE THREAD

**Issue by acoppock** [DeclareDesign/DeclareDesign#3]
no mands, one mator,
one mand one mator,
two mands one mator,

no mands, two mators,
one mand two mators,
two mands two mators

**Comment by graemeblair** [comment]
from @acoppock:

# One to One

Estimand: ATE
Estimator: Difference-in-means

# One to One (variant)

Estimand: Difference-in-CATEs
Estimator: OLS (coef on interaction term)


# One to Two

Estimand: ATE
Estimator 1: Difference-in-means
Estimator 2: OLS with controls

# Two to One

Estimand 1: ATE
Estimand 2: E[ATT]
Estimator: DIM

# Two to two (not crossed!)

Estimand 1: CATE|Men
Estimand 2: CATE|Women
Estimator 1: DIM|Men
Estimator 2: DIM|Women


# Two to Two (crossed!)

Estimand 1: ATE
Estimand 2: E[ATT]
Estimator 1: Difference-in-means
Estimator 2: OLS with controls

We'd want 4 mand-mator pairs here


# Many DVs, Same estimator

Estimand 1: ATE on Y1
Estimand 2: ATE on Y2

...

Estimand k: ATE on Yk

Estimator 1: DIM on Y1
Estimator 2: DIM on Y2
...
Estimator k: DIM on Yk

# A true regression model

Estimands 1-k: k-length vector of true regression coefficients
Esimators 1-k: The fitted coefficients from OLS
