### ISSUE TITLE
tidy_estimator

### ISSUE THREAD

**Issue by macartan** [DeclareDesign/DeclareDesign#300]
are there cases where tidy_estimator is not wanted? If not, does this need to be explicit here?

handler = tidy_estimator(estimator_function)

this would be nicer if possible:

handler = estimator_function

**Comment by nfultz** [comment]
The difference is the interface - not all functions are valid step handlers.


if your specific estimator_function returns a data.frame with  estimand labels / coefficients correctly filled it, it doesn't need to be wrapped. 

If your specific estimator function returns something untidy, such as a single number, it isn't a valid handler. Handlers must be data.frame in, data.frame out.

**Comment by macartan** [comment]
OK thanks for this.
