### ISSUE TITLE
disappearing diagnosis

### ISSUE THREAD

**Issue by macartan** [DeclareDesign/DeclareDesign#301]
I have a design that produces the following simulations df using simulate_design 

```
> sims_df
  design_label sim_ID estimand_label    estimand estimator_label         est coefficient        se         p   ci_lower  ci_upper
1       design      1        control -0.06675827              A1 -0.06334958        <NA>        NA        NA         NA        NA
2       design      1            ate  0.17865929              A2  0.13914128           Z 0.2603802 0.5944165 -0.3782478 0.6565304
> diagnose_design(sims_df)
```

Note the <.NA.> for coefficient for A1. ( A1 uses a custom function and A2 uses Y~Z.)

There should be two rows to the diagnosis, but there is only 1:

```
Research design diagnosis based on 1 simulations. Diagnosand estimates with bootstrapped standard errors in parentheses (100 replicates).

 Design Label Estimand Label Estimator Label Coefficient N Sims   Bias   RMSE  Power Coverage Mean Estimate SD Estimate Mean Se
       design            ate              A2           Z      1  -0.04   0.04   0.00     1.00          0.14          NA    0.26
                                                                (0.00) (0.00) (0.00)   (0.00)        (0.00)          NA  (0.00)

```

If I remove the <.NA.> it will work alright.

What is better behavior? Treat NA as a value when creating sets for diagnosis?

**Comment by nfultz** [comment]
Can you set the name of coefficient for A1 to be (Intercept) or similar in
your custom estimator?

**Comment by macartan** [comment]
Yes I can do that for sure and it works, but cannot expect users to figure
this. I think, unless there are risks, better if diagnose_design fills in
NAs; or at least throws an error.

Note in this case coefficient is not needed since the estimates labels are
provided

**Comment by nfultz** [comment]
I think having some estimators that include coefficients and some that don't is going to expose other bugs downstream - should add that as an error or at least a warning as a design validation for declare_estimator steps.
