### ISSUE TITLE
attrition_variables

### ISSUE THREAD

**Issue by macartan** [DeclareDesign/DeclareDesign#302]
attrition_variables is an argument for reveal_outcomes but it is not documented. 
In practice it seems natural now to treat attrition like any other potential outcome and not have special functions for it. Is there a reason to support this?

**Comment by nfultz** [comment]
It's legacy behavior from before I started, I'm fine with handling it the
regular way though.

**Comment by graemeblair** [comment]
I agree it seems natural but it's a pain to do it on your own because you need to have a switch to generate it -- so it seemed like a case for limited helper

**Comment by nfultz** [comment]
Since attrition can only have two levels (NA or not) you don't need the general purpose switching equation, you could just use ifelse.

**Comment by graemeblair** [comment]
?declare_reveal already documents the attrition_variables argument and provides an example. Closing for now.
