### ISSUE TITLE
term

### ISSUE THREAD

**Issue by macartan** [DeclareDesign/DeclareDesign#304]
I think we have problems with the current "term" approach for estimates taken from a model

 * First the estimands get odd names (`(Intercept)`) 
 * Second the estimands are  a pain to name  as you need to consult with model output; and the names are and not in the spirit of estimands based on potential outcomes
 * Third it seems to run into issues when combined with other appraoches as shown below
 * Fourth we don't need it. We are already able to do the same thing in a simpler way, see below

Is there anything against the simpler approach below?

```
# The issue:

population  <- declare_population(N = 100, X = rnorm(N))
potentials  <- declare_potential_outcomes(Y ~ (.25 + X) * Z + rnorm(N))
assignment  <- declare_assignment(m = 50)
design_stub <- population +  potentials + assignment + declare_reveal()

estimands_regression <- declare_estimand(
  `(Intercept)` = mean(Y_Z_0),
  `Z` = mean(Y_Z_1 - Y_Z_0),
  term = TRUE,
  label="Regression_Estimands")

estimators_regression <- declare_estimator(
  Y ~ Z,
  estimand = estimands_regression,
  model = lm,
  term = TRUE
)

estimand_2  <- declare_estimand(ATE = mean(Y_Z_1 - Y_Z_0),   label = "ate_simple")
estimator_2 <- declare_estimator(Y~Z, estimand = estimand_2, label = "dim")

design <- design_stub + estimands_regression + estimators_regression  + estimand_2 + estimator_2

# This has four rows instead of 3
simulate_design(design, sims = 1)

# This produces a warning and fails to connect estimates to estimand for dim
diagnose_design(design, sims = 2)

# Note that constituent parts work ok when declared separately
design_A <- design_stub + estimand_2 + estimator_2
diagnose_design(design_A, sims = 2)

design_B <- design_stub + estimands_regression + estimators_regression
diagnose_design(design_B, sims = 2)
```

# A simpler, better approach?

* Getting rid of term from the estimands declaration seems a lot simpler and gives users control over names
* Then in estimates declaration give the estimands of interest. "term" is a bit of a funny term for term. 
* With this usage, the older term "coefficients"  seems more accurate

```

estimands_regression <- declare_estimand(
  Q1 = mean(Y_Z_0),
  Q2 = mean(Y_Z_1 - Y_Z_0),
  label="Regression_Estimands")

estimators_regression <- declare_estimator(
  Y ~ Z,
  estimand = c("Q1", "Q2"),
  model = lm,
  term = TRUE
)

design <- design_stub + estimands_regression + estimators_regression + estimand_2 + estimator_2

# Now fine
simulate_design(design, sims = 1)

# Now fine
diagnose_design(design, sims = 2)

# To boot: nice flexibility to access different estimands 
estimator_3 <- declare_estimator(Y~Z, estimand = c(estimand_2, "Q2"), label = "dim2")
diagnose_design(design + estimator_3,  sims = 20)
```

**Comment by nfultz** [comment]
Right now, the author of the design needs to choose whether they want a "term" column as an extra dimension on estimands / estimates in output. Mixing and matching is not really well defined or tested afaik. Arguably it could be made smarter, but the most correct way would require changing the internal representation of instances of estimates from a single data frame to a set or list of data frames, and then merging each seperately by the object graph specified by the design.  It's probably better to add some declare time warnings around this.   


Re `declare_estimand(term=)` / naming

In base R,  `term` is for variables in a model formula (eg `Gender`),  `coef` / coefficients is for actual output after whatever contrasts / transformations are applied (`GenderF`). I agree that coef is somewhat more accurate, but I believe @acoppock had made that change to match broom's output.

 
Re: `declare_estimator(estimand=, term=)` arguments -

I don't think users should have to spell out every single individual estimand they want to reference in declare_estimator  just to get the merge to work correctly, as many real world models have dozens if not hundreds of parameters. I'm not a fan of `(Intercept)` either, but that is to match lm/glm in base R, there's nothing we can do about that. Other packages may follow other conventions. Your alternative would be to manually create a constant and use that explicitly, which you can name whatever you like.

We also should not encourage anyone providing estimands  to mix  character and objects. That should be a declare time error eg if there were ambiguous or duplicated estimands provided. Also a run time warning if any of those estimands weren't actually used. Arguably we should get rid of character mode entirely but it may have uses for very complicated designs - it adds nothing in very simple designs IMHO. 

I also think a better default would be for declare_estimator to check the  term = TRUE on the estimand step being linked at declare time, and use that value if term wasn't explicitly provided. I thought it already did that. 

Also note that if `term =` were to be removed,  the following is ambiguous - how does one specify which estimand goes with the constant? 

```
estimator_3 <- declare_estimator(Y~Z, estimand = c(estimand_2, "Q2"), label = "dim2")
```

**Comment by macartan** [comment]
Thanks a lot Neal.  Very helpful.

I think we agree on this:
* There are instances where declaring multiple estimates in a block is
efficient; eg if they draw on parameters estimated from a single model.
(eg imagine a structural model and then a set of parameter transformations
that one cares about). In that case rather than rerunning the model many
times a user would efficiently just want to export a k*s matrix of s
statistics for each of k estimates.
* There are instances, similarly, where declaring multiple estimands in a
block could be efficient. I have seen this especially for spillover
examples where multiple estimands might depend on similar calculations (say
spillover = declare_estimands(All = Y(1,1,1) -  Y(0,0,0) ,  One = Y(1,0,0)
-  Y(0,0,0) ,  Not_one = Y(1,1,1) -  Y(0,1,1) , Uniformity = Y(0,0,0)) etc.
In such cases using declare_estimand once to create k estimands is handy.

The question is how to match in such cases and to do so in a way that does
not require in general that a single estimand declaration  has exactly the
k estimates in a single estimator declaration.

I like the character labelling because it lets you pick out exactly the
estimands you want. SO in this case you can flexibly add : estimands =
("All", "One," "Uniformity) to the estimator declaration with an implied 1
to 1 ordered mapping between  estimates and estimands.

I understand you see ambiguity issues here but I am not quite seeing them.

A.
e.g. you say: following is ambiguous - how does one specify which estimand
goes with the constant?

estimator_3 <- declare_estimator(Y~Z, estimand = c(estimand_2, "Q2"),
label = "dim2")

I would think here that
(a) if as written (without  term = TRUE) there is only one estimate here
and so this is a case with one estimator shooting at two estimands
(b) with term  = TRUE (or term otherwise picking out a collection of
coefficients) then there should be  a one to one ordered mapping.
estimands_2 goes with the constant, Q2 goes with the beta
(c) if the coefficient list is not 1 and not the same length as the
estimand list then there should be an error

B.
is there also in principle ambiguity if you have multiple "ATE" estimands
defined  inside different estimand declarations? If that is the concern
then I would rather that not be allowed; ie you get a complaint if your
design uses the same character label for estimands inside different calls.
Otherwise to disambiguate one might imagine my_estimand::ATE. THough I'd
prefer keeping labels unique.

Currently we can do all this though I do worry that you see ambiguities

**Comment by nfultz** [comment]
The ambiguity is mostly from joining on a combination of estimands x estimators by term where names do not match exactly, and instead falls back default behavior.

eg these four are all different and the difference is unobvious:

```
1. (estimand a,b ) x estimator (c,d )
2. (estimand a,b term=true) x estimator (c,d )
3. (estimand a,b ) x estimator (c,d, term=true )
4.  (estimand a,b term=true) x estimator (c,d term=true)
 ```

2 and 3 should be at least a warning because of differences in the columns in the output.


re B
the ambiguity comes from two places:
  - the stock behavior of silently dropping the intercept, which allows common 1:1 and 1:many merges proceed
  -  the two term=T/F 'modes', one where estimands labels should be unique, and the other where estimand label - coefficent  pairs are unique.  

At the minimum we should write out all 8 combos and make sure they look ok.

**Comment by acoppock** [comment]
Here's my attempt at @nfultz's four varieties.

``` r
library(DeclareDesign)
#> Loading required package: randomizr
#> Loading required package: fabricatr
#> Loading required package: estimatr

population  <- declare_population(N = 100, X = rnorm(N))
potentials  <- declare_potential_outcomes(Y ~ (.25 + X) * Z + rnorm(N))
assignment  <- declare_assignment(m = 50)
design_stub <- population +  potentials + assignment + declare_reveal()

# 1. (estimand a,b ) x estimator (c,d )
mand_1 <- declare_estimand(Q1 = mean(Y_Z_0),
                           Q2 = mean(Y_Z_1 - Y_Z_0),
                           label = "mand_1")
                           
mator_1 <- declare_estimator(Y ~ Z, model = lm_robust, estimand = c("Q1", "Q2"))
design_1 <- design_stub + mand_1 + mator_1

# this applies the ATE estimate to both estimands 
# (i.e., is nonsensiscal, but is perhaps correct behavior?)
simulate_design(design_1, sims = 1)
#>   design_label sim_ID estimand_label    estimand estimator_label term
#> 1     design_1      1             Q1 -0.05545665       estimator    Z
#> 2     design_1      1             Q2  0.51131136       estimator    Z
#>   estimate std.error statistic   p.value   conf.low conf.high df outcome
#> 1 0.295802 0.2433117  1.215733 0.2270072 -0.1870421 0.7786462 98       Y
#> 2 0.295802 0.2433117  1.215733 0.2270072 -0.1870421 0.7786462 98       Y

# 2. (estimand a,b term=true) x estimator (c,d )
mand_2 <- declare_estimand(
  `(Intercept)` = mean(Y_Z_0),
  `Z` = mean(Y_Z_1 - Y_Z_0),
  term = TRUE,
  label = "mand_2"
)

mator_2 <- declare_estimator(Y ~ Z, model = lm_robust, estimand = mand_2)
design_2 <- design_stub + mand_2 + mator_2

# doesn't seem to work
simulate_design(design_2, sims = 1)
#>   design_label sim_ID estimand_label        term   estimand
#> 1     design_2      1         mand_2           Z 0.16757963
#> 2     design_2      1         mand_2 (Intercept) 0.08405545
#>   estimator_label  estimate std.error statistic    p.value    conf.low
#> 1       estimator 0.4647511 0.2473721  1.878753 0.06325026 -0.02615077
#> 2            <NA>        NA        NA        NA         NA          NA
#>   conf.high df outcome
#> 1 0.9556529 98       Y
#> 2        NA NA    <NA>

# 3. (estimand a,b ) x estimator (c,d, term=true )

mand_3 <- declare_estimand(Q1 = mean(Y_Z_0),
                           Q2 = mean(Y_Z_1 - Y_Z_0),
                           label = "mand_3")

mator_3 <- declare_estimator(Y ~ Z, model = lm_robust, estimand = c("Q1", "Q2"), term = TRUE)

design_3 <- design_stub + mand_3 + mator_3

# WORKS
simulate_design(design_3, sims = 1)
#>   design_label sim_ID estimand_label   estimand estimator_label
#> 1     design_3      1             Q1 0.11351171       estimator
#> 2     design_3      1             Q2 0.08434008       estimator
#>          term  estimate std.error statistic   p.value   conf.low conf.high
#> 1 (Intercept) 0.1744578 0.1678964  1.039080 0.3013244 -0.1587272 0.5076427
#> 2           Z 0.1714273 0.2708048  0.633029 0.5281892 -0.3659760 0.7088306
#>   df outcome
#> 1 98       Y
#> 2 98       Y

# 4.  (estimand a,b term=true) x estimator (c,d term=true)

mand_4 <- declare_estimand(
  `(Intercept)` = mean(Y_Z_0),
  `Z` = mean(Y_Z_1 - Y_Z_0),
  term = TRUE,
  label = "mand_4"
)

mator_4 <- declare_estimator(
  Y ~ Z,
  estimand = mand_4,
  model = lm_robust,
  term = TRUE, label = "mator_4"
)

design_4 <- design_stub + mand_4 + mator_4

# works
simulate_design(design_4, sims = 1)
#>   design_label sim_ID estimand_label        term  estimand estimator_label
#> 1     design_4      1         mand_4 (Intercept) 0.2108486         mator_4
#> 2     design_4      1         mand_4           Z 0.2063561         mator_4
#>    estimate std.error statistic    p.value    conf.low conf.high df
#> 1 0.0574023 0.1374421 0.4176473 0.67711867 -0.21534701 0.3301516 98
#> 2 0.4125134 0.2370964 1.7398552 0.08502386 -0.05799669 0.8830234 98
#>   outcome
#> 1       Y
#> 2       Y
```

Created on 2018-08-16 by the [reprex
package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by nfultz** [comment]
That is the four cases where names match correctly, I think it will be different if you name the estimand "ATE"

**Comment by acoppock** [comment]
Thanks Neal -- I'll look into that.

Here is from @macartan.  I think the most proximate problem is this one. It *simulates* both designs but does not *diagnose* both designs, because "term" is *correctly* NA for the second design.  We need to figure out how to handle the group_by in diagnose design for this.  It's not immediately clear how to group by a column that is NA for only some rows.

``` r
library(DesignLibrary)
design_1 <- simple_factorial_designer(N = 500, outcome_means = c(0,0,1,2), w_A = 0, w_B = 0)
design_2 <- multi_arm_designer(N = 500, m_arms = 3, means = c(0, 0, 1))
simulate_design(design_1, design_2, sims = 2)
#>    design_label sim_ID  estimand_label    estimand estimator_label term
#> 1      design_1      1           ate_A  0.93281625  No_Interaction    A
#> 2      design_1      1           ate_B  0.02750076  No_Interaction    B
#> 3      design_1      1     interaction  1.05592171     Interaction  A:B
#> 4      design_1      2           ate_A  0.90837068  No_Interaction    A
#> 5      design_1      2           ate_B -0.03262725  No_Interaction    B
#> 6      design_1      2     interaction  1.16075699     Interaction  A:B
#> 7      design_2      1 ate_Y_Z_2_Y_Z_1 -0.10018217             DIM <NA>
#> 8      design_2      1 ate_Y_Z_3_Y_Z_1  0.98358148             DIM <NA>
#> 9      design_2      1 ate_Y_Z_3_Y_Z_2  1.08376365             DIM <NA>
#> 10     design_2      2 ate_Y_Z_2_Y_Z_1 -0.05613567             DIM <NA>
#> 11     design_2      2 ate_Y_Z_3_Y_Z_1  1.02003677             DIM <NA>
#> 12     design_2      2 ate_Y_Z_3_Y_Z_2  1.07617245             DIM <NA>
#>       estimate  std.error  statistic      p.value   conf.low  conf.high
#> 1   1.43024519 0.09503922 15.0489996 1.914531e-42  1.2435170 1.61697336
#> 2   0.58495762 0.09503922  6.1549076 1.548721e-09  0.3982294 0.77168579
#> 3   1.16645692 0.18288975  6.3779238 4.116788e-10  0.8071228 1.52579108
#> 4   1.56514254 0.09694195 16.1451518 1.896428e-47  1.3746760 1.75560911
#> 5   0.52287137 0.09694195  5.3936542 1.069666e-07  0.3324048 0.71333794
#> 6   1.15119179 0.18706205  6.1540637 1.558564e-09  0.7836601 1.51872351
#> 7  -0.06405785 0.11306868 -0.5665393 5.714166e-01 -0.2864932 0.15837746
#> 8   0.99737823 0.11282344  8.8401683 6.126576e-17  0.7754230 1.21933344
#> 9   1.06143608 0.12001456  8.8442275 5.601107e-17  0.8253486 1.29752354
#> 10 -0.11667089 0.10620697 -1.0985238 2.727868e-01 -0.3256087 0.09226692
#> 11  0.93100624 0.10326912  9.0153404 1.623639e-17  0.7278581 1.13415436
#> 12  1.04767713 0.10974666  9.5463232 3.130756e-19  0.8317859 1.26356834
#>          df outcome coefficients   N alpha   design
#> 1  497.0000       Y           NA  NA    NA     <NA>
#> 2  497.0000       Y           NA  NA    NA     <NA>
#> 3  496.0000       Y           NA  NA    NA     <NA>
#> 4  497.0000       Y           NA  NA    NA     <NA>
#> 5  497.0000       Y           NA  NA    NA     <NA>
#> 6  496.0000       Y           NA  NA    NA     <NA>
#> 7  326.4014       Y  -0.06405785 334  0.05 Standard
#> 8  325.4817       Y   0.99737823 333  0.05 Standard
#> 9  330.9998       Y   1.06143608 333  0.05 Standard
#> 10 325.8798       Y  -0.11667089 333  0.05 Standard
#> 11 330.3030       Y   0.93100624 334  0.05 Standard
#> 12 330.0335       Y   1.04767713 333  0.05 Standard
diagnose_design(design_1, design_2, sims = 2, bootstrap_sims = FALSE)
#> 
#> Research design diagnosis based on 2 simulations.
#> 
#>  Design Label Estimand Label Estimator Label Term  Bias RMSE Power
#>      design_1          ate_A  No_Interaction    A  0.47 0.47  1.00
#>      design_1          ate_B  No_Interaction    B  0.46 0.46  1.00
#>      design_1    interaction     Interaction  A:B -0.00 0.03  1.00
#>  Coverage Mean Estimate SD Estimate Mean Se Type S Rate Mean Estimand
#>      0.00          1.51        0.03    0.10        0.00          1.04
#>      0.00          0.47        0.08    0.10        0.00          0.01
#>      1.00          0.99        0.01    0.19        0.00          1.00
#>  N Sims
#>       2
#>       2
#>       2
```

Created on 2018-08-16 by the [reprex
package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by macartan** [comment]
One fix as suggested in other issue is to replace the NAs with sthg else,
effectively making them a stratum.

**Comment by acoppock** [comment]
Yes, that's exactly the approach i took here: https://github.com/DeclareDesign/DeclareDesign/pull/310

It does fix the problem, and I'm not sure if there are downsides?

**Comment by macartan** [comment]
Only downside I see if there is a false conflation of a term called "NA"
with an imputed "NA". It seems unlikely as generally either all or none are
NA in a stratum.

**Comment by macartan** [comment]
Great.

I think the problem with the original issue is still there though? This arises in the creation of the simulations data frame, in a single design when term is used for some estimators but not others (this is quite a plausible situation). Simplified example below.


```
population  <- declare_population(N = 100, Z = rep(0:1,50), Y = rnorm(N))

estimands_regression <- declare_estimand(
  `(Intercept)` = 0,
  `Z` = 1,
  term = TRUE,
  label="Regression_Estimands")

estimators_regression <- declare_estimator(
  Y ~ Z,
  estimand = estimands_regression,
  model = lm,
  term = TRUE
)

estimand_2  <- declare_estimand(ATE = 2,   label = "2")
estimator_2 <- declare_estimator(Y~Z, estimand = estimand_2, label = "dim")

design <- population + estimands_regression + estimators_regression  + estimand_2 + estimator_2

# This has four rows instead of 3: Rows 3 and 4 are not merging properly
simulate_design(design, sims = 1)
```

**Comment by acoppock** [comment]
via @macartan , this still doesn't work:

```
population  <- declare_population(N = 100, Z = rep(0:1,50), Y = rnorm(N))

estimands_regression <- declare_estimand(
  `(Intercept)` = 0,
  `Z` = 1,
  term = TRUE,
  label="Regression_Estimands")

estimators_regression <- declare_estimator(
  Y ~ Z,
  estimand = estimands_regression,
  model = lm,
  term = TRUE
)

estimand_2  <- declare_estimand(ATE = 2,   label = "2")
estimator_2 <- declare_estimator(Y~Z, estimand = estimand_2, label = "dim")

design <- population + estimands_regression + estimators_regression  + estimand_2 + estimator_2

# This has four rows instead of 3: Rows 3 and 4 are not merging properly
simulate_design(design, sims = 1)
```

**Comment by acoppock** [comment]
We're thinking that a possible fix would be to merge *first* by estimand-estimator pair, then stack.

**Comment by macartan** [comment]
Still having issues here? Most recent example below

```

library(DesignLibrary)

base <- multi_arm_designer(N = 10,m_arms = 5)

diagnose_design(base, sims = 2)


factors     <- declare_step(fabricate, Control = 1*(Z==1), 
                            A = 1*(Z %in% c(3,5)), 
                            B = 1*(Z %in% c(4,5)))

interaction_estimand <- declare_estimand(
  interaction = mean((Y_Z_5 - Y_Z_4) - (Y_Z_3 - Y_Z_2)))

interaction_estimator <- declare_estimator(
  Y ~ A*B, model = lm_robust,  term = "A:B", 
  estimand = "interaction", label = "interaction", subset = Control!=1)                                

design <- base  + factors + interaction_estimand + interaction_estimator
simulate_design(design, sims = 1)
diagnose_design(design, sims = 3)
```

**Comment by graemeblair** [comment]
As far as I can tell, the only issue is that the `multi_arm_designer` is spitting out a `coefficients` column in its estimates, which is from an old version of DD, so should be renamed to `estimate`. I'm closing this, but if there was something else wrong in the output of this example @macartan let us know.

**Comment by graemeblair** [comment]
sorry that was wrong, it should be `coefficients` -> `estimate`
