### ISSUE TITLE
Designers in dd documentation

### ISSUE THREAD

**Issue by macartan** [DeclareDesign/DeclareDesign#306]
-- use designers in dd documentation to shorten examples
-- in expand_design given example where argument is a vector; eg
    designs <- expand_design(multi_arm_designer, means = list(c(3,2,4), c(1,4,1)))

**Comment by acoppock** [comment]
I've added the proposed line to the `expand_design` docs in https://github.com/DeclareDesign/DeclareDesign/pull/319.

I don't think I have clarity on when we should use full declarations versus designers. I prefer full declarations to designers except when iterating over parameters. This is mostly a taste thing.

**Comment by nfultz** [comment]
Each of the steps should obv use the appropriate steps directly.  I think simulate / diagnose could use designers instead though.
