### ISSUE TITLE
minor: change printing (and maybe diagnosis df) from "estimand_label" -> "estimand"

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/DeclareDesign#309]
We waste lots of space saying "Estimand Label" rather than "Estimand" and "Design Label" etc. Propose we change all print objects to drop "Label" and perhaps also just to name things shorter in these cases when we create the diagnoses. Thoughts?

**Comment by nfultz** [comment]
For pretty printing column names in tabular output this is a good idea.

For long format output might as well leave the "label" in there since it
takes a whole block of lines per step / design anyway. Shorter names are
generally good though.

**Comment by macartan** [comment]
Am all for shorter names

**Comment by nfultz** [comment]
Would we then have to change diagnosis to 

```
estimand   estimand_value
       Q                3
```

Seems marginal then.

**Comment by graemeblair** [comment]
Agreed @nfultz that seems bad.
