### ISSUE TITLE
quick_design misinterprets arguments

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/DeclareDesign#31]
If you send:

```
my_designs <- quick_design(
  template = my_template_function, 
  my_variable = seq(from = 0, to = .20, by = .05))
```

It will send you back three designs -- one with 0 [i.e. the from], one with .2 [i.e. the to], and one with .05 [i.e. the by]. It should have expanded seq to be the vector 0, .05, .1, .15, .2 and made 5 designs.

**Comment by acoppock** [comment]
fixed in b08efa4499a0d996176c499976f5460edfe328d0

needed to un-lazy it
