### ISSUE TITLE
low sims warning

### ISSUE THREAD

**Issue by macartan** [DeclareDesign/DeclareDesign#326]
* Give warning for low sims even if sim is provided as scalar

**Comment by graemeblair** [comment]
oops. thanks. will correct.

**Comment by graemeblair** [comment]
MWE without a warning:

`diagnose_design(simple_two_arm_designer(), sims = 1)`

**Comment by graemeblair** [comment]
we had only done this if you had a fan out strategy i.e. sims = c(1,1,1) would get a warning, but not if it was a single number sims = 1. opening PR with this minor change.
