### ISSUE TITLE
allow multiple estimands by sending list of estimands to declare_estimator()

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/DeclareDesign#33]
<a href="https://github.com/graemeblair"><img src="https://avatars.githubusercontent.com/u/3320015?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [graemeblair](https://github.com/graemeblair)**
_Monday Dec 14, 2015 at 20:27 GMT_
_Originally opened as https://github.com/DeclareDesign/DeclareDesign-dev/issues/183_

----

then when estimates function returns a matrix with M columns and you sent a list of length M in declare_estimator, it compares estimates in column 1 to estimand 1 in list, etc.

**Comment by jaspercooper** [comment]
implemented now
