### ISSUE TITLE
Queries re DeclareDesign

### ISSUE THREAD

**Issue by oscci** [DeclareDesign/DeclareDesign#333]
I've got a few questions about DeclareDesign so I created a .rmd file, which you can find as 'simplereg' here:
https://github.com/oscci/deevybee_repo

I'm not experienced at using github except as a repository for files, but hope this allows you to find the file, which is also there as knitted html.
Thanks.

**Comment by jaspercooper** [comment]
Hi @oscci, thanks so much for reaching out! I'm having a look through the Rmd and will try to get back to you with some assistance today or tomorrow at the latest.

**Comment by nfultz** [comment]
I'll pull quote a couple questions and try to address them.

> This is all good until the potential_outcomes step. I think it’s confusing to refer to Y_t2 and Z before they have been defined.

> The Inquiry step had me baffled. I can understand what is computed here (difference in values of Y at t2 for the two groups), but again, the problem I have is that Y_t2_Z_1 and Y_t2_Z_0 are nowhere defined in the script. I can easily compute them, but how do we know what variable names we can put into an inquiry?

> Anyhow, what I need to know is how does the script know that there is an object Y_t2_Z_1? Where does it come from? This would help explain what things can be used as estimands when formulating other models.

> The Inquiry step had me baffled. I can understand what is computed here (difference in values of Y at t2 for the two groups), but again, the problem I have is that Y_t2_Z_1 and Y_t2_Z_0 are nowhere defined in the script. I can easily compute them, but how do we know what variable names we can put into an inquiry?

> What does declare_reveal do? What does declare_step do?

I think a common theme of these questions is that the various steps in that example are pretty opaque and rely on default behavior.

To get a feel for what each step is doing, I'd really recommend running the steps manually:

    df <- population()
    head(df)
    df2 <- potential_outcomes(df)
    head(df2)

and so on. You should find in df2 that the P.O. step added Y_t2_Z_0 and Y_t2_Z_1 to df. The potential outcomes function uses the LHS of the formula for the variable prefix, and the assignment_variable defaults to Z to form the suffix. 

Hopefully this is enough to get you unstuck.


I'm going to close out this ticket since this isn't really a bug or feature request, but if you have more questions like this, please do ask them over at http://discuss.declaredesign.org/

**Comment by jaspercooper** [comment]
@oscci if you don't mind I'm going to put a commented version of your RMD at the link Neal provided, does that work?

**Comment by oscci** [comment]
Yes, please do. And I will use that forum in future. 
I'm optimistic the steer from jasper will get me unstuck: I had not appreciate that those functions created a df. 
Thanks to both for your help.

**Comment by macartan** [comment]
I think we need a post that really walks through the pipe structure,
showing what objects get generated and get passed along. It's not obvious
especially when defaults are used

**Comment by oscci** [comment]
It all makes perfect sense once that is explained, but it's cryptic for a newcomer starting out. It seems exciting with great potential, but you'll need an idiot's guide if it is going to be widely used. I'm good at doing that sort of thing and am happy to give it a go when I get a moment.

**Comment by macartan** [comment]
Well that would be amazing!

**Comment by oscci** [comment]
OK. If you look https://github.com/oscci/deevybee_repo, the simplereg.rmd now provides a walkthrough for beginners, which I've knitted to .html. Please do let me know of any errors you find in it and feel free to correct them.

**Comment by macartan** [comment]
This is really great. We need to think about the best way to share this.
Very generous of you.

I don't see any errors. I might use kable for prettier table output and
might define coverage as "Prob that ci contains estimands" rather than
"Prob estimand within ci" to be on the safe side. The distinction between
sd_estimate and mean_se might be highlighted (nicely, here, they are very
close)

For us for the designer: isn't it more more natural and correct to do

declare_assignment(prob  = 1 - attrition_rate)

rather than

declare_assignment(m = round(N * (1 - attrition_rate))

**Comment by jaspercooper** [comment]
This is really fantastic, thanks @oscci 

I'd propose compiling this as a `github_document` [following these directions](https://rmarkdown.rstudio.com/github_document_format.html), and then posting the md.

@macartan I agree about your point with the `attrition_rate` parameter. I had actually meant to correct this in a patch. Issuing in DesignLib

**Comment by jaspercooper** [comment]
@oscci and @macartan I can go ahead and implement some proposed changes (kable, etc.) and PR them into @oscci's repository for review, if you both like?

**Comment by oscci** [comment]
Please do feel free to do modifications and post this where it will be most useful.

One thing I was not sure of was whether I'd got the correct definition at the end for 'bias' - there are two kinds of bias in the pdf draft paper and I took the first one.

If you let me know when it is in shape and public, I can tweet about it.

**Comment by jaspercooper** [comment]
Awesome, see PR. can't thank you enough for the wonderful job you did walking people carefully through the software.

**Comment by oscci** [comment]
Thanks Jasper.
I've just uploaded to Github a new version with a more sensible name incorporating your changes and few other tweaks, i.e. DeclareDesignIntro.rmd

I was confused by the bit you added re definition of the estimand - but I then thought it through and I think I'm right in saying that we can just drop the 2nd part of the more complicated estimand based on difference-of-differences, because in the model the expected value for mean(Y_t1_Z_1-Y_t1_Z_0) is zero. Not sure that's right, but happy to have further modification.

Here's what it now says:
 We could also define the estimand as the true underlying difference-in-differences,i.e. = mean(mean(Y_t2_Z_1 - Y_t2_Z_0) - mean(Y_t1_Z_1 - Y_t1_Z_0)). However, since our model assumes no difference between groups in Y at time 1, we can drop the second part of this term.

Best wishes

Dorothy

On 20 Sep 2018, at 10:16, Jasper Cooper <notifications@github.com<mailto:notifications@github.com>> wrote:


Awesome, see PR. can't thank you enough for the wonderful job you did walking people carefully through the software.

**Comment by macartan** [comment]
great:

FWIW my take on the estimand question is that there is value in trying to
define the estimand as the quantity of interest independent of the assumed
dgp. (the dependence is on the "signature" of the model -- ie the set of
variables and their values, but not on the functional relations between
them)

the reason for this is that it means that someone else can come along and
say: how will this work if the dgp is different to what you speculated?
they shouldn't have to alter the "question" when they alter the model.

(the spillover post we just put up is an interesting one which highlights
the classic definition of the ATE does in fact pressuppose a model with no
spillovers and that makes it hard as a general matter to ask how a design
would fare in the presence of spillovers)
