### ISSUE TITLE
add error to declare_diagnosands

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/DeclareDesign#34]
Funny business happens if you don't name your diagnosands, i.e.

```diagnose_design(design, diagnosands = declare_diagnosands(mean(est)), sims = 5, bootstrap = FALSE)```

returns

```
Research design diagnosis

 Estimand Label Estimator Label X2.15482663672757
            ATE    my_estimator          2.154827
```

So let's add an error in `declare_diagnosands` if they are not named.

**Comment by graemeblair** [comment]
This errors now: 
`Error in names(options)[1] <- label : replacement has length zero`

**Comment by nfultz** [comment]
This should be a declaration time validation on declare_diagnosands.
