### ISSUE TITLE
draw_assignment and draw_sample

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/DeclareDesign#347]
two functions similar to draw_estimates_data that 

1) draw_assignment: take data and then add assignment variable(s) (and assignment probs), running all assignment steps
2) draw_sample: take data and subset to sample (with inclusion probs), potentially more than once

**Comment by nfultz** [comment]
These would be easy.  If they won't be running the population steps, maybe add a _data suffix to match up with draw_estimates_data.

**Comment by macartan** [comment]
I think we want

get_xx for applying XX to data
And
draw_xx for generating data and applying  XX

So draw_assignment generates data up to the point of assignment and then
assigns whereas get_assignment does a possibly real assignment in real data
(even though it is a draw from possible assignments)

How about a situation where you have data up to set m and want to implement
steps beyond  m + 3?
