### ISSUE TITLE
add new option changeable to declare_design

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/DeclareDesign#35]
```declare_design(pop, assign, modifiable = c("m", "n"))```

when you do

```
m <- 5
n <- 2000
pop <- declare_population(N = n)
assign <- declare_assignment(m = m)
d <- declare_design(pop, assign, modifiable = c("m", "n")
```

then it allows you to use this syntax

```
modify_design(d, m = 25, n = 1000)
```

to change the values of m and n in the design. 

This also allows

```
quick_design(d, m = c(25, 50), n = seq(100, 1000, 100))
```

which creates a list of designs, modifying m and n for each one.

This will (hopefully!) obviate the need for template functions.

**Comment by nfultz** [comment]
Alternative syntax that might be easier to operate with:

```
m <- 5
n <- 2000
pop <- declare_population(N = free(n))
assign <- declare_assignment(m = free(m))
d <- declare_design(pop, assign)
```

This would mean that the design function is now `function(n=2000,m=5)` rather than `function()`.
