### ISSUE TITLE
Thoughts about `expand_design` documentation.

### ISSUE THREAD

**Issue by aaronrudkin** [DeclareDesign/DeclareDesign#363]
Been using expand_design a lot, it's a godsend for medium size simulations, it's really very slick. Great job. Skip to the bottom to hear a suggestion about documentation, or read my user story.

**Two parameters, each a scalar**
I have a design with two parameters (A and B), and I want to do the convex combination of a sequence of values for each -- i.e. A={1, 2, 3}, B={1, 2, 3}, please generate 9 designs total. An example parameterization is A=2, B=1. This is pretty simple. Either just pass the arguments, or check the documentation and see `expand`'s default value covers this. :+1: There could probably be an example below using multiple parameters to decode what "crossproduct" and "recycle" mean, but overall this case is easy.

**Parameters where a parameter is itself a vector**

Now, suppose the arguments are actually A={{1, 2, 3}, {4, 5, 6}, {7, 8, 9}}, B = {1, 2, 3}, so an example design is A={4, 5, 6}, B = 2. How do I pass the arguments? Nothing in the documentation makes it obvious, but I take a shot in the dark and assume I pass A as a list of vectors and the iterator expand_design uses will pass a vector at a time. It works! Here I think again a documentation example would be great.

**Pairwise sets of parameters**

Imagine I want to run the designs: (A=2, B=1), (A=2, B=4), (A=3, B=4), (A=4, B=8). In my real example, certain values of B are illegal given a value of A and I want to exclude them from running because error handling is hard and I don't want to think about it. 

My initial thought was, maybe I put a list of paired vectors, i.e. `list(c(A = 2, B=1), c(A=2, B=4), ...)` but that is extremely un-R-ish, and also part-way through writing I realized I was being dumb, and I should pass them as vectors: A=c(2, 2, 3, 4), B = c(1, 4, 4, 8), and then pass `expand=FALSE`.

The reason I didn't think of this initially is because the documentation for `expand` says "... otherwise recycle them", and of course here what I'm doing is not exactly "recycling" the variables. Recycling to me connotes the vectors being of unequal lengths and the short vector repeating when it exhausts. What I'm actually doing by choosing `expand=FALSE` is jointly iterating over A and B, instead of taking the cross product. Again, an example below the argument docs would also be useful.

**Conclusion**

Here are my suggestions based on my experience.

1. Change the documentation for the `expand` argument to something like: "(Boolean). Default TRUE. If true, forms the crossproduct of the `...` arguments, combining each value of each argument with each value of every other argument. If FALSE, pairs arguments, combining the first value of the first argument with the first value of each other argument. If FALSE and arguments have unequal length, the shorter arguments are recycled."

2. Add examples below that include both `expand = FALSE` and `expand = TRUE` with multiple parameters.

Hope this is useful feedback. v0.10.0, CRAN installation, but checked current master branch to ensure the docs are the same still.

**Comment by macartan** [comment]
+1
