### ISSUE TITLE
inconsistency in var names

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/DeclareDesign#364]
we have

`declare_potential_outcomes(assignment_variables = c("Z1", "Z2"))`

and

`declare_reveal(assignment_variables = c(Z1, Z2))`

Let's go to all quoted

**Comment by macartan** [comment]
I'd prefer to keep
This change could break a lot of code
Plus there's a kind of logic. In the first case this is a label, z doesn't
exist necessarily. In the second case you are manipulating existing
variables

**Comment by nfultz** [comment]
Both PO and reveal process assignment_variables through the reveal_nse helper - the behavior should be identical, both steps work with charcter, symbol and  !! unquoting AFAIK.

Is this ticket instead about consistency in documentation?

**Comment by graemeblair** [comment]
Thanks @nfultz you're right. All are available.

@macartan I just think it's very confusing for users when we mix -- which are they supposed to use? do they mean something different? (they do not). let's keep it all, but in the library and elsewhere let's use character strings unless we need the !! unquoting.

**Comment by macartan** [comment]
so if nothing is going to break then fine

**Comment by graemeblair** [comment]
yes - suggesting leaving as is in code, changing practice moving forward
