### ISSUE TITLE
proposal for better interface for models and post-estimation steps

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/DeclareDesign#375]
Currently, it's hard / impossible to string together a statistical model like `lm_robust` and any post-estimation step other than choosing one or more of the coefficients as quantities of interest. The only way to do this now (I think) is to write your own custom estimator function that does both inside a function you write and returns tidy outputs. So you do `lm_robust` and then `car::linearHypothesis` for example. 

A big change that would enable these to be split, and thus easier to do and more transparent (the subsetting and tidy'ing is hidden now more or less, would be to carry around models objects between steps. 

Right now, we have a results df that at each step may be added to if there are estimates or estimands created. Instead, at each step there is a results *environment*. Inside it, there is an estimates-estimands df that works as currently. But in addition you can stick model fits (i.e. the output of `lm_robust`) into the environment. 

There would be two new user functions:
1) `declare_model(Y ~ Z + X, model = lm_robust, se_type = "HC3")` .  -- returns an lm_robust object which is a list
2) `declare_postestimation("Z + 2*X = 0", handler = linear_hypothesis)` -- returns a tidy df with the coefficient for Z plus 2 * the coefficient for X and an s.e. etc.

We could still preserve the existing `declare_estimator` which would let you provide tidy estimator functions. And by default we could still have the `term` interface, the simplest postestimation choice.

I imagine this will create a lot of problems and break things. But a big problem right now is that we're demanding everyone specify their quantities of interest and target them at the right estimands, and it's currently very hard to do that for common quantities of interest that don't simply pop out of a regression as a coefficient estimate.

Thoughts?

**Comment by nfultz** [comment]
Replies inline:

> Currently, it's hard / impossible to string together a statistical model like lm_robust and any post-estimation step other than choosing one or more of the coefficients as quantities of interest. The only way to do this now (I think) is to write your own custom estimator function that does both inside a function you write and returns tidy outputs. So you do lm_robust and then car::linearHypothesis for example.

"Postestimation" is a stata-ism with procedural connotations, and not necessarily an idea worth bringing in to DD. We should let the user specify what they want, and not force them to specify how to do it. Much like how SQL is a declaration of data to pull out of a database.

> A big change that would enable these to be split, and thus easier to do and more transparent (the subsetting and tidy'ing is hidden now more or less, would be to carry around models objects between steps.

Splitting them should be fine in principle, but in practice the post-estimation functions all have very different interfaces, so there's basically little chance of mixing-and-matching working very well.

> Right now, we have a results df that at each step may be added to if there are estimates or estimands created. Instead, at each step there is a results environment. Inside it, there is an estimates-estimands df that works as currently. But in addition you can stick model fits (i.e. the output of lm_robust) into the environment.

Not exactly accurate, but close enough.

Execution state is defined here:
https://github.com/DeclareDesign/DeclareDesign/blob/master/R/design_helper_functions.R#L174-L187




> 
> There would be two new user functions:
> 
> declare_model(Y ~ Z + X, model = lm_robust, se_type = "HC3") . -- returns an lm_robust object which is a list
> declare_postestimation("Z + 2*X = 0", handler = linear_hypothesis) -- returns a tidy df with the coefficient for Z plus 2 * the coefficient for X and an s.e. etc.

"Models" aren't necessarily a well defined concept / api to code against in R. Will probably just have to assume they are blobs of data. 

car::linear_hypothesis doesn't work with lots of packages, for example. Even then, you get F-tests, which might not be what people really want.

Also consider how these need to fit in the larger framework. What if someone want more than one model? More than one postestimate? this is introducing another many:many complexity into the "design object graph", to say nothing of hooking postestimates up to estimands in the 9 or so cases we support.  

Realistically, I think it would end up looking more like this:

    declare_postestimation("Z + 2*X = 0", postestimate = linear_hypothesis, 
                                          estimand="my_estimand", model="my_model")

> We could still preserve the existing declare_estimator which would let you provide tidy estimator functions. And by default we could still have the term interface, the simplest postestimation choice.

I think there's enough value in the existing code to keep it. 

> I imagine this will create a lot of problems and break things. 

Yes.

> But a big problem right now is that we're demanding everyone specify their quantities of interest and target them at the right estimands, and it's currently very hard to do that for common quantities of interest that don't simply pop out of a regression as a coefficient estimate.

Ultimately people will still have to specify that somehow - now they will have to specify the models (by name?), which postestimates use which models, and link those to specific estimands. 

I think the main reason it is hard is not that it is actually complicated (I knocked out more than a dozen examples in less than a day), it is lack of good documentation. One of the goals for DesignLibrary was to preroll most of the common adjustments, but it isn't there yet. And also diagnosis being a bit buggy. 

Here are some ideas worth considering:

  * Is a "model" anything other than arbitrary data coming out of arbitrary / user-provided functions? What is the minimum that it must support to count? tidy() ?
  * "Postestimates" - how are they different from estimates? Are they just estimates based on other estimates? Do they need to be diagnosed differently?
  * Some r packages can do nested models in one pass, others need extra steps? Will their declare'd designs look very different? 
    * This is a sign that we are letting *implementation concerns leak into the higher level*.


  * Can we imagine better syntax ?

    my_design <- population + sampling + model1 / post1 + model2 / post2

    * uses operator precedence to group posthoc to models. Not obvious how to do eg LRTs with that sytanx.
    * could do something similar to link estimands to estimators? IDK. 
  * Could DesignLibrary address the same pain more directly?
    
        declare_estimator("Z + 2*X = 0", handler=DesignLibrary::linear_hypothesis_handler)

**Comment by macartan** [comment]
>
-

Could DesignLibrary address the same pain more directly?

declare_estimator("Z + 2*X = 0",
handler=DesignLibrary::linear_hypothesis_handler)


@Jasper Cooper <jjc2247@columbia.edu>  @Clara Bicalho Maia Correia
<clara.bicalho@nyu.edu> @Lily Medina <lilymiru@gmail.com>  this isn't the
kind of thing we have in the library at the moment
Can we have a designer that has a test as an argument? That might be useful
for pointing the way forward prior to a general solution
Or Clara is this something that could be imagined as a step in the sandbox?
