### ISSUE TITLE
"meta-diagnosands"

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/DeclareDesign#381]
The minimum detectable effect for a design is, in our framework, a summary of diagnosands across a set of designs where you vary a single parameter, effect size. I think there's probably a broader set of "meta-diagnosands" that are of the form "find the optimal design among these designs subject to a constraint." We can do this via diagnose_design then our own code. We could also have a wrapper for diagnose_design that takes diagnosands and then meta-diagnosands that would run the diagnosis and then do the additional step of simulation. Not sure if worth it, but MDE is an extremely common use case. From the output you could get the power curve (via get_diagnosands) but it would also print the MDE.

**Comment by jaspercooper** [comment]
This is a very cool idea. Were you thinking a parametric meta-diagnosand (i.e. fit significant_pval ~ effect_size as a logit or something and then solve for effect given power = .8), or just the minimum of the effects that you simulated that got you a power above .8?

**Comment by graemeblair** [comment]
This is the kind of dplyr pipeline I had in mind:

```
designs <- expand_design(my_designer, effect_size = seq(0, 1, by = .1))
diagnosis <- diagnose_designs(designs)
get_diagnosands(diagnosis) %>% 
  arrange(power) %>% 
  filter(power >= 0.8) %>% 
  slice(1) %>% 
  mutate(mde = effect_size)
```

**Comment by macartan** [comment]
that's a nice way to think about it; nice to package it up somehow

you could also though think of a single design in which there is a distribution of effects -- we have a few examples of that already; (most simply  `declare_potential_outcomes(Y~ runif(1)*Z + u)` )

the hard thing though is given the simulation you need some way of choosing the cutoff ; 

here is an approach using Jasper's suggestion; nice thing here is that it is applied to a single design in the usual way so you can assess how MDE changes over designs; it also has the advantage of being continuous rather than depending on the effects in a sequence of designs

```
d <- 
  declare_population(N = N, u = rnorm(N)/2) +
  declare_potential_outcomes(Y ~ runif(1)*Z + u) +
  declare_estimand(ate = mean(Y_Z_1 - Y_Z_0))+
  declare_assignment() + 
  declare_reveal() +
  declare_estimator(Y~Z)

f <- function(p.value, estimand) {
  S <- p.value < 0.05
  M <- glm(S ~ estimand , family = "binomial")
  -(coef(M)[1] + log(.25))/(coef(M)[2])
  }

mde = declare_diagnosands(mde = f(p.value,  estimand), keep_defaults = FALSE)
d <- set_diagnosands(d, mde)

designs <- redesign(d, N = c(20, 100))
```
Then simply:
```
> diagnose_design(designs, sims = 1000)

Research design diagnosis based on 1000 simulations. Diagnosand estimates with bootstrapped standard errors in parentheses (100 replicates).

 Design Label   N Estimand Label Estimator Label Term N Sims    Mde
     design_1  20            ate       estimator    Z   1000   0.67
                                                             (0.01)
     design_2 100            ate       estimator    Z   1000   0.30
                                                             (0.01)
```

**Comment by nfultz** [comment]
EDIT:

When comparing with classic power.t.test, you have to divide n by 2:

```
t(Vectorize(power.t.test)(n=c(20,30,60,100)/2, sd = .5, power = .8, sig.level = .05))[,1:5]
     n  delta        sd  sig.level power
[1,] 10 0.6624728196 0.5 0.05      0.8  
[2,] 15 0.5298903107 0.5 0.05      0.8  
[3,] 30 0.3678144508 0.5 0.05      0.8  
[4,] 50 0.2829410876 0.5 0.05      0.8  
```

**Comment by nfultz** [comment]
I think this would make an interesting blog post. +1
