### ISSUE TITLE
set_diagnosands diagonsands not passed on by simulate_design

### ISSUE THREAD

**Issue by macartan** [DeclareDesign/DeclareDesign#382]
Example:

```
d <- 
  declare_population(N = 20, u = rnorm(N)/2) +
  declare_potential_outcomes(Y ~ runif(1)*Z + u) +
  declare_estimand(ate = mean(Y_Z_1 - Y_Z_0))+
  declare_assignment() + 
  declare_reveal() +
  declare_estimator(Y~Z)

mde = declare_diagnosands(q= mean(estimand[(p.value > 0.04) &  (p.value < 0.06)]),
                          keep_defaults = FALSE)
d <- set_diagnosands(d, q)

# This generates the correct diagnosands
diagnose_design(d)

# This does not
s <- simulate_design(d, sims = 200)
diagnose_design(s)
```

**Comment by graemeblair** [comment]
hadn't thought of that possible use, will fix thx

**Comment by graemeblair** [comment]
This is a bit tricky. `simulate_design` can take one or more designs, how would we want the following cases to be handled:

1) single design, has diagnosands -- easy, keep them;
2) multiple designs, all have same diagnosands -- easy, keep them;
3) multiple designs, one has diagnosand others dont -- ?
4) multiple designs, more than one different set of diagnosands -- seems best to drop them

Given all this complexity, it seems like we might want to not enable this (it will sometimes work and other times not). Open to other views.

**Comment by nfultz** [comment]
agreed, if we evaluated diagnosands D_A from design A on simulations from
unrelated design B, D_A(B) seems quite likely to break. For example if B
doesn't provide confidence intervals.

**Comment by graemeblair** [comment]
closing this for now, feel free to reopen
