### ISSUE TITLE
push patch 0.16.0 to CRAN

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/DeclareDesign#388]
I'm going to push a new version this weekend based on the new features `draw_assignment` and `draw_sample` and `draw_data(design, start = 2, data = my_step_1_data)`; as well as many bug fixes - especially on factors in diagnoses.

Please reply here if you have other issues you think must be addressed before pushing this time!

**Comment by nfultz** [comment]
It would be nice if the older branch containing a plot method for designs could get merged in. Low priority though.

**Comment by graemeblair** [comment]
Taking a look!

**Comment by graemeblair** [comment]
It has some bugs -- often doesn't print all the steps in the design. There's now a new branch that runs with the current version of DD but will need some more serious debugging. Will try to prioritize this over the next couple weeks after this patch is released.
