### ISSUE TITLE
some draw_assignment* issues

### ISSUE THREAD

**Issue by macartan** [DeclareDesign/DeclareDesign#390]
# draw_sample error if no sampling?

```
set.seed(1)
library(DesignLibrary)
design <- two_arm_designer()
df <- draw_data(design)
draw_sample(design, data = df)

Error in design[[i]] : subscript out of bounds
```

# Inconsistent data from draw_assignment

Y is no longer consistent with Z and potential outcomes.  Wise perhaps to remove or replace data produced *after*  assignment?
```
> head(draw_assignment(design, df))
   ID        u_0        u_1      Y_Z_0     Y_Z_1 Z Z_cond_prob          Y
1 001 -0.6264538 -0.6264538 -0.6264538 0.3735462 1         0.5 -0.6264538
2 002  0.1836433  0.1836433  0.1836433 1.1836433 0         0.5  0.1836433
```

**Comment by graemeblair** [comment]
Thanks, will fix the first

On the second, definitely see the logic but that doesn't seem possible -- you can't detect from the design what variables it will create. draw_assignment only sees the design and the df so not enough info to know Y is the only one that's post-assignment in this case for example.

**Comment by macartan** [comment]
I can see the issues on the second.

Would one approach be to give people the option of just producing the assignment vector -- that might be what they expect from this command anyhow. So, eg have a combine = FALSE default and produce a dataframe with ID, and the assignments (though imaginably there is also data produced between assignment steps that might be needed).. With combine = TRUE return all available data. ?

If we cant do anything, maybe a warning?

**Comment by nfultz** [comment]
> On the second, definitely see the logic but that doesn't seem possible -- you can't detect from the design what variables it will create. draw_assignment only sees the design and the df so not enough info to know Y is the only one that's post-assignment in this case for example.

There should be metadata on each assignment, potential_outcomes and reveal step for which variables it depends on, and which they are creating - that is how the automatic revealing was implemented.

**Comment by graemeblair** [comment]
Decided to remove this function, with the new way we're doing reveal outcomes there is no way to avoid this (and no good way even to detect that it happened to throw a warning). For same reason dropping draw_sample.
