### ISSUE TITLE
Error applying 'diagnose_designs()' to multi_arm_designer 

### ISSUE THREAD

**Issue by clarabicalho** [DeclareDesign/DeclareDesign#402]
Running into error with `diagnose_designs()` applied to list of multi-arm designers. No idea what's causing it, any help really appreciated!

```
library(DesignLibrary) #CRAN version
all_designs <- expand_design(multi_arm_designer, N = c(100, 120))
diagnose_designs(all_designs)
```

```
sessionInfo()
```

R version 3.4.4 (2018-03-15)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets 
[6] methods   base     

other attached packages:
[1] DesignLibrary_0.1.2.9999 DeclareDesign_0.17.0    
[3] estimatr_0.14            fabricatr_0.6.0         
[5] randomizr_0.16.1        

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.0         codetools_0.2-15  
 [3] listenv_0.7.0      future_1.8.0      
 [5] digest_0.6.15      rlang_0.3.0.1     
 [7] future.apply_0.2.0 generics_0.0.2    
 [9] Formula_1.2-3      tools_3.4.4       
[11] parallel_3.4.4     yaml_2.1.18       
[13] compiler_3.4.4     globals_0.11.0

**Comment by nfultz** [comment]
What's the error message?

**Comment by clarabicalho** [comment]
>Error in `[.data.frame`(simulations_df, , reorder_columns(parameters_df,  : 
  undefined columns selected

**Comment by clarabicalho** [comment]
@nfultz or anyone else, were you able to reproduce this error? Anything I can do on library side?

**Comment by acoppock** [comment]
I can confirm I can reproduced the error... am looking into it now!

**Comment by acoppock** [comment]
Ok, i think I see the source of the error -- 

the estimator in `multi_arm_designer` returns a column called `N` which then conflicts with the parameter `N`.  see here for a demo:

```
design <- multi_arm_designer(N = 100)
Browse[2]> run_design(design)
$estimates_df
  coefficients std.error       df  N  statistic   p.value   conf.low conf.high alpha
1   0.11089031 0.2200281 60.19807 67  0.5039826 0.6161132 -0.3292016 0.5509822  0.05
2   0.05997452 0.2932090 59.14469 66  0.2045453 0.8386297 -0.5267054 0.6466544  0.05
3  -0.05091579 0.2702678 50.76060 67 -0.1883902 0.8513220 -0.5935631 0.4917315  0.05
  outcome condition2 condition1   design estimator_label estimand_label    estimate
1       Y          2          1 Standard DIM (Z_2 - Z_1)      ate_Y_2_1  0.11089031
2       Y          3          1 Standard DIM (Z_3 - Z_1)      ate_Y_3_1  0.05997452
3       Y          3          2 Standard DIM (Z_3 - Z_2)      ate_Y_3_2 -0.05091579

$estimands_df
  estimand_label estimand
1      ate_Y_2_1        0
2      ate_Y_3_1        0
3      ate_Y_3_2        0
```

I think that column could be names `N compared` or something similar to deconflict.  This is clearly an instance of a general problem I don't know how to solve, i.e., that If the estimator has a column with the same name as a parameter, we have a problem!

**Comment by clarabicalho** [comment]
Thanks for looking into this @acoppock! I edited the multi_arm_designer to avoid this issue and included tests to the library to make sure we're not running into the same thing again.

**Comment by graemeblair** [comment]
Looks like this was already resolved
