### ISSUE TITLE
Enhancement: Consort Diagrams from Design Objects

### ISSUE THREAD

**Issue by jwbowers** [DeclareDesign/DeclareDesign#403]
Just recording a possible enhancement to ease reasoning about and communication of a research design. (Consort Diagrams are one option: 
http://www.consort-statement.org/consort-statement/flow-diagram)

**Comment by macartan** [comment]
maybe ref https://declaredesign.org/blog/2018-12-11-meta-analysis.html

**Comment by jwbowers** [comment]
Looks like a few packages to help with this: 
https://www.google.com/search?q=consort+diagram+r&ie=UTF-8&oe=UTF-8&hl=en-us&client=safari

**Comment by graemeblair** [comment]
I like this idea a lot. 

We've worked a bit on a visual representation of the flow of a design object in this branch and will give this some more thought: https://github.com/DeclareDesign/DeclareDesign/tree/plot-method-redux
