### ISSUE TITLE
allow explicitly linking PO, assignment, and reveal

### ISSUE THREAD

**Issue by nfultz** [DeclareDesign/DeclareDesign#41]
Right now, the link between potential outcomes is by variable naming conventions:

```
pop <- declare_population(N=500)
poutcome <- declare_potential_outcome(Y_Z_1=1, Y_Z_2=2)
assn <- declare_assignment(m=50)
my_reveal <- reveal_outcome 

design <- declare_design(
  pop,
  poutcome,
  assn,
  my_reveal
)
```

```
pop <- declare_population(N=500)
poutcome <- declare_potential_outcome(Y~3+5*Z)
assn <- declare_assignment(m=50, potential_outcomes=poutcome)
my_reveal <- reveal_outcome (assignment=assn)

design <- declare_design(
  pop,
  poutcome,
  assn,
  my_reveal
)
```

This could let us avoid having to recreate column names with `paste` 
- declare_assignment could interrogate the potential outcome for the name of the assignment variable, and what values it could take
- reveal_outcomes could ask assignment which columns it created, which columns that points to, and use those to construct the final outcome column

**Comment by graemeblair** [comment]
Thanks Neil. We've been down this road and found various problems with it. In general, we were trying to minimize typing for the user. 

We have a 90%-completed alternative solution that does away with reveal_outcomes by default in the validate branch. Would you be able to take a look and see if you could merge it in? 

The basic logic is that it creates a validate_function in declare_design in addition to summary_function etc. that runs at the moment of declaration. In this validation, a key step is that it checks whether any outcomes need to be revealed at each step and adds a reveal_outcomes step at that point if needed. Happy to answer questions or run through it with you as useful.

**Comment by nfultz** [comment]
Sure, which branch is it on?

**Comment by nfultz** [comment]
nevermind, found it on `validate`

**Comment by nfultz** [comment]
It seems like the logic for `validate_design()` as it's written on [1] is to reveal as soon as possible in the pipeline - are there cases where that would not be immediately after a `declare_assignment` step?



[1]: https://github.com/DeclareDesign/DeclareDesign/blob/79de825f9406448a08c2cc178fe646a4937196b3/R/design_helper_functions.R#L45

**Comment by nfultz** [comment]
Maybe a simpler way to do it is to always reveal after the assignment, unless the user specifically turns it off (eg `reveal=FALSE` or something)

**Comment by nfultz** [comment]
Above functionality was implemented.
