### ISSUE TITLE
dplyr::mutate() causing a problem with diagnosing simulations dfs

### ISSUE THREAD

**Issue by jaspercooper** [DeclareDesign/DeclareDesign#410]
Often you want to `mutate()` a simulations df before diagnosing (for example, simulation-level p-value adjustment). 

Something a bit weird happening when you use `dplyr::mutate()` on a simulations df and pass it to `diagnose_design()`. Piping into `data.frame()` or `as.data.frame()` doesn't appear to fix it.

MWE:

```r
library(tidyverse)
design <- 
  declare_population(
    N = 100, 
    X1 = rnorm(N),
    X2 = rnorm(N)
  ) +
  declare_estimand(true_effect = 0) +
  declare_estimator(X1 ~ X2, model = lm_robust, estimand = "true_effect", label = "X1 on X2") 

simulations <-   
  simulate_design(design, sims = 20) %>% 
  mutate(a = 1) 

diagnose_design(simulations)
```

Gives me: `Error in fix.by(by.y, y) : 'by' must specify a uniquely valid column`

**Comment by jaspercooper** [comment]
I don't think it's a general `dplyr` or tibble issue. This works fine:

```r
simulations <-   
  simulate_design(design, sims = 20) %>% 
  ungroup() 

diagnose_design(simulations)
```

**Comment by jaspercooper** [comment]
also works
```r
simulations <-   
  simulate_design(design, sims = 20) %>% 
  mutate() %>% 
  ungroup() 

diagnose_design(simulations)
```

**Comment by nfultz** [comment]
dplyr is stripping the `parameters` attribute, and causing a merge to fail.
This looks straightforward to fix.

**Comment by jaspercooper** [comment]
OK great, thanks for the quick explanation. Think it's worth fixing for things like this (writing reply now with your temporary fix): http://discuss.declaredesign.org/t/correcting-p-values-with-the-holm-correction/93

**Comment by jaspercooper** [comment]
Happy to work on a patch btw if you can give me some guidance on what would be the best way to fix, @nfultz
