### ISSUE TITLE
warning from rlang 0.2

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/DeclareDesign#414]
Get this when running tests in RStudio:

```
test-alternative-df-compatibility.R:38: warning: tibble more
Assigning non-quosure objects to quosure lists is soft-deprecated.
Please coerce to a bare list beforehand with `as.list()`
This warning is displayed once per session.
```

Cannot reproduce in session or figure out in the code where that is. The line has to do with declare_reveal 

see https://github.com/r-lib/rlang/issues/658

**Comment by jaspercooper** [comment]
Some others I've come across using dev version of rlang (0.3.0 I think?)

test_designers.R:16: warning: (unknown)
Assigning non-quosure objects to quosure lists is deprecated as of rlang 0.3.0.
Please coerce to a bare list beforehand with `as.list()`
This warning is displayed once per session.

test_designers.R:16: warning: (unknown)
`quo_expr()` is deprecated as of rlang 0.2.0.
Please use `quo_squash()` instead.
This warning is displayed once per session.

test_designers.R:36: warning: binary_iv_designer's default design runs.
`is_lang()` is deprecated as of rlang 0.2.0.
Please use `is_call()` instead.
This warning is displayed once per session.

test_designers.R:36: warning: binary_iv_designer's default design runs.
`lang_name()` is deprecated as of rlang 0.2.0.
Please use `call_name()` instead.
This warning is displayed once per session.

test_designers.R:36: warning: block_cluster_two_arm_designer's default design runs.
`lang_modify()` is deprecated as of rlang 0.2.0.
Please use `call_modify()` instead.
This warning is displayed once per session.

**Comment by jaspercooper** [comment]
these calls don't exist anywhere in designlibrary source code, I think they're from DD internals

**Comment by graemeblair** [comment]
I think this is caused by estimatr see https://github.com/DeclareDesign/estimatr/issues/307
