### ISSUE TITLE
change to allow version 3.4

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/DeclareDesign#424]
Hi all - I think we should set up our travis setups to test against as many versions of R as possible (probably now back to 3.4) and try to make the software work backwards that far. Currently, it's impossible to install if you have 3.4 and there are many people who cannot upgrade for office IT reasons.  I plan to do this across all packages.

**Comment by jaspercooper** [comment]
Yes I just had this issue with a colleague, agree completely.

**Comment by graemeblair** [comment]
Also should update the docs with two methods for installing old version:

devtools::install_version("randomizr", version = "0.12.0", repos = "http://cran.us.r-project.org")

and using MRAN.

**Comment by graemeblair** [comment]
We now are at R 3.5, which is quite a long time ago. I suggest we try to keep it at 3.5 as long as we can; it's in the test matrix for DeclareDesign.
