### ISSUE TITLE
declare_sampling(filter = FALSE) option

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/DeclareDesign#427]
Suggesting an option for declare_sampling that turns on/off the filter/subset step. When setting up sampling-dependent estimands that are *out of sample* you have to not use declare_sampling to get at them. This would be easy change I think.

**Comment by nfultz** [comment]
Instead of `filter=TRUE/FALSE` I would recommend `keep=0/1/0:1` (maybe `take` or `select` would be a better name) - this is slightly more general in that you can take the sample, the complement of the sample, or both. If sampling strategies were extended to return other values than just 0/1, this would handle that as well.


This would then be a one line change, just change

https://github.com/DeclareDesign/DeclareDesign/blob/master/R/declare_sampling.R#L66

to be 

    data[[S]] %in% keep

and no need to mess with flow control.

**Comment by graemeblair** [comment]
Thanks @nfultz. Interesting. What non-0/1 values are you imagining would be provided in future?

Do others have views on this as a feature change? @macartan @acoppock @jaspercooper

**Comment by jaspercooper** [comment]
My view is I would like this as a feature change, don't have strong views
on the particular implementation.

**Comment by nfultz** [comment]
> Thanks @nfultz. Interesting. What non-0/1 values are you imagining would be provided in future?
> 
> Do others have views on this as a feature change? @macartan @acoppock @jaspercooper

IDK, maybe if people wanted to use the multi-arm assignment functions, and then cherry pick some arms - this could let you get really specific with the block-level probabilities and not require the user to aggregate them just to be compatible with declare_sampling's slightly different interface. I could see that being useful for simulating sequential designs / contextual bandits when the time dimension spans multiple rows ("long format").

**Comment by graemeblair** [comment]
Makes sense, thanks.

**Comment by nfultz** [comment]
Based on the question from the forum, we should probably un-hardcode the name of the sampling indicator as well - then people can pass that column to an estimator's `subset=` argument - this _should_ let people compare sampling strategies within-design.

**Comment by graemeblair** [comment]
I thought it wasn't hard-coded, i.e. we have:

```
sampling_handler <- function(data, ..., sampling_variable = "S") {
```

?

**Comment by nfultz** [comment]
That's the sampling prob, not the indicator of actually being sampled in a random draw.

**Comment by graemeblair** [comment]
Not following. Or perhaps the code doesn't do what I thought it did. `assignment_variable` in declare_assignment is the indicator for which condition you are assigned to (and also is used to name the condition prob i.e. Z_cond_prob). `sampling_variable` similarly is supposed to be the indicator for whether you are sampled though we don't currently create that (and it also used to construct the variable name for the sampling probability S_inclusion_prob).

**Comment by nfultz** [comment]
https://github.com/DeclareDesign/DeclareDesign/blob/master/R/declare_sampling.R#L53

It's hard coded for reasons I don't recall, we should just make it S / sampling variable.
