### ISSUE TITLE
print.declared_object function

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/DeclareDesign#43]
We used to have a summary_code(my_design) function, which spit out the code for your design. It basically just spit out the declare_X() calls. It strikes me the following would be more useful:

```
> my_estimator <- declare_estimator(Y ~ Z)
> get_code(my_estimator)

difference_in_means(formula = Y ~ Z, alpha = 0.05)
```

Which basically prints the function name you declared (explicitly or implicitly) and the default options you are implicitly using for that function (using formals etc.). 

I think this should print out immediately after each declare_X call, so you see what you just declared. We could make this the print method for each function created by DeclareDesign (we'd have to add an S3 class to each function), or name the function something else like `print_code`.

Thoughts?

**Comment by acoppock** [comment]
maybe it’s the summary() of each declaration? Along maybe with other interesting info?

**Comment by nfultz** [comment]
We are already tagging the result of `declare_*` with some metadata, I
think an additional class would be appropriate too, as well as a
`print.declare_thing` class - ideally, we could reuse the same print method
across all of the different `declare_*` HOFs. The interaction would then be
more like:


    > my_estimator <- declare_estimator(Y ~ Z)
    > my_estimator

    DeclareDesign estimator:
        difference_in_means(formula = Y ~ Z, alpha = 0.05)

**Comment by graemeblair** [comment]
That looks great to me, Neal!

**Comment by graemeblair** [comment]
Just recording our convo here, that @nfultz will work on this for tomorrow (if possible)

**Comment by nfultz** [comment]
As of #150 - the print method for steps now prints out the call which constructed it. eg

```
> d[[1]]
declare_population(N = N, foo = rnorm(N))
```

the print method of a full design currently routes through `summary.design()`
