### ISSUE TITLE
Throw an error if estimand label is specified, but there's no associated estmand

### ISSUE THREAD

**Issue by acoppock** [DeclareDesign/DeclareDesign#430]

**Comment by nfultz** [comment]
IIRC, right now we allow this, but there will be missing cells in the diagnostics table? I could imagine that being used intentionally  where you are comparing multiple estimators w/o a ground truth - but seems totally reasonable to throw a warning, especially to catch typos and the like. Most of the design checks were broken or silenced in the switch to plus signs, probably worth redoing that subsystem.
