### ISSUE TITLE
tweak to allow adjusting treatment effect in regression_discontinuity_designer

### ISSUE THREAD

**Issue by aeggers** [DeclareDesign/DeclareDesign#434]
Hello, just playing around with the regression_discontinuity_designer, I note that it is written in a way that prevents the user from adjusting tau, the treatment effect, via redesign().

For example, 

`rdd_1 <- regression_discontinuity_designer()`
`diagnose_design(rdd_1)`
`rdd_2 <- rdd_1 %>% redesign(tau = 1.5)` 
`diagnose_design(rdd_2)`

They give the same results even though the second tau is 10X the first.

I think the issue is that tau does not appear directly in the declare_potential_outcomes step, but instead appears via a function called treatment(). redesign() apparently does not rerun the functions that appear inside of the declare steps. If you instead put the guts of the treatment() function inside the declare_potential_outcomes step, redesign() works as it should.

**Comment by macartan** [comment]
yes; this is a dangerous feature of redesign
thanks for the catch

**Comment by jaspercooper** [comment]
Fixed in recent patch. Thanks @aeggers !
