### ISSUE TITLE
Parallel computations with the future package do not use reproducible RNGs

### ISSUE THREAD

**Issue by svraka** [DeclareDesign/DeclareDesign#448]
Running simulations and bootstraps after `set.seed` makes computations reproducible on a single core. However, when using the parallel package, reproducibility breaks.

Sorry, this not a proper reprex, I don't know how set this up in a single script. Save this code as `seed_save.R`:

```r
suppressPackageStartupMessages({
  library(DeclareDesign)
  library(DesignLibrary)
  library(future)
})

set.seed(1234)

design <- two_arm_designer()
diagnosis <- diagnose_design(design, sims = 100)
saveRDS(diagnosis, sprintf("diagnosis_%s.RData", Sys.getenv("R_FUTURE_PLAN")), compress = FALSE)
```

And then run this:

```r
suppressPackageStartupMessages({
  library(DeclareDesign)
  library(DesignLibrary)
  library(future)
})

callr::rscript("seed_save.R", env = c(callr::rcmd_safe_env(), R_FUTURE_PLAN = "sequential"))
callr::rscript("seed_save.R", env = c(callr::rcmd_safe_env(), R_FUTURE_PLAN = "multicore"))

diagnoses <- lapply(list.files(pattern = "diagnosis.+\\.RData"), readRDS)
mapply(identical, diagnoses[[1]], diagnoses[[2]])
#>       simulations_df       diagnosands_df     diagnosand_names 
#>                FALSE                FALSE                 TRUE 
#>         group_by_set        parameters_df bootstrap_replicates 
#>                 TRUE                 TRUE                FALSE 
#>       bootstrap_sims 
#>                 TRUE
```

<sup>Created on 2020-11-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
<details>
<summary>
Session info
</summary>

    devtools::session_info()
    #> ─ Session info ───────────────────────────────────────────────────────────────
    #>  setting  value                       
    #>  version  R version 4.0.3 (2020-10-10)
    #>  os       Ubuntu 20.04.1 LTS          
    #>  system   x86_64, linux-gnu           
    #>  ui       X11                         
    #>  language (EN)                        
    #>  collate  en_US.UTF-8                 
    #>  ctype    en_US.UTF-8                 
    #>  tz       Etc/UTC                     
    #>  date     2020-11-03                  
    #> 
    #> ─ Packages ───────────────────────────────────────────────────────────────────
    #>  package       * version date       lib source        
    #>  assertthat      0.2.1   2019-03-21 [1] RSPM (R 4.0.0)
    #>  backports       1.2.0   2020-11-02 [1] CRAN (R 4.0.3)
    #>  callr           3.5.1   2020-10-13 [1] RSPM (R 4.0.2)
    #>  cli             2.1.0   2020-10-12 [1] RSPM (R 4.0.2)
    #>  codetools       0.2-17  2020-10-17 [3] CRAN (R 4.0.3)
    #>  crayon          1.3.4   2017-09-16 [1] RSPM (R 4.0.0)
    #>  DeclareDesign * 0.22.0  2020-03-24 [1] RSPM (R 4.0.0)
    #>  desc            1.2.0   2018-05-01 [1] RSPM (R 4.0.0)
    #>  DesignLibrary * 0.1.4   2019-06-17 [1] RSPM (R 4.0.0)
    #>  devtools        2.3.2   2020-09-18 [1] RSPM (R 4.0.2)
    #>  digest          0.6.27  2020-10-24 [1] RSPM (R 4.0.3)
    #>  ellipsis        0.3.1   2020-05-15 [1] RSPM (R 4.0.0)
    #>  estimatr      * 0.26.0  2020-09-07 [1] RSPM (R 4.0.2)
    #>  evaluate        0.14    2019-05-28 [1] RSPM (R 4.0.0)
    #>  fabricatr     * 0.10.0  2019-09-04 [1] RSPM (R 4.0.0)
    #>  fansi           0.4.1   2020-01-08 [1] RSPM (R 4.0.0)
    #>  Formula         1.2-4   2020-10-16 [1] RSPM (R 4.0.2)
    #>  fs              1.5.0   2020-07-31 [1] RSPM (R 4.0.2)
    #>  future        * 1.20.1  2020-11-03 [1] CRAN (R 4.0.3)
    #>  generics        0.1.0   2020-10-31 [1] RSPM (R 4.0.3)
    #>  globals         0.13.1  2020-10-11 [1] RSPM (R 4.0.2)
    #>  glue            1.4.2   2020-08-27 [1] RSPM (R 4.0.2)
    #>  highr           0.8     2019-03-20 [1] RSPM (R 4.0.0)
    #>  htmltools       0.5.0   2020-06-16 [1] RSPM (R 4.0.1)
    #>  httr            1.4.2   2020-07-20 [1] RSPM (R 4.0.2)
    #>  knitr           1.30    2020-09-22 [1] RSPM (R 4.0.2)
    #>  listenv         0.8.0   2019-12-05 [1] RSPM (R 4.0.0)
    #>  magrittr        1.5     2014-11-22 [1] RSPM (R 4.0.0)
    #>  memoise         1.1.0   2017-04-21 [1] RSPM (R 4.0.0)
    #>  parallelly      1.21.0  2020-10-27 [1] RSPM (R 4.0.3)
    #>  pkgbuild        1.1.0   2020-07-13 [1] RSPM (R 4.0.2)
    #>  pkgload         1.1.0   2020-05-29 [1] RSPM (R 4.0.0)
    #>  prettyunits     1.1.1   2020-01-24 [1] RSPM (R 4.0.0)
    #>  processx        3.4.4   2020-09-03 [1] RSPM (R 4.0.2)
    #>  ps              1.4.0   2020-10-07 [1] RSPM (R 4.0.2)
    #>  R6              2.5.0   2020-10-28 [1] RSPM (R 4.0.3)
    #>  randomizr     * 0.20.0  2019-09-06 [1] RSPM (R 4.0.0)
    #>  Rcpp            1.0.5   2020-07-06 [1] RSPM (R 4.0.2)
    #>  remotes         2.2.0   2020-07-21 [1] RSPM (R 4.0.2)
    #>  rlang           0.4.8   2020-10-08 [1] RSPM (R 4.0.2)
    #>  rmarkdown       2.5     2020-10-21 [1] RSPM (R 4.0.3)
    #>  rprojroot       1.3-2   2018-01-03 [1] RSPM (R 4.0.0)
    #>  sessioninfo     1.1.1   2018-11-05 [1] RSPM (R 4.0.0)
    #>  stringi         1.5.3   2020-09-09 [1] RSPM (R 4.0.2)
    #>  stringr         1.4.0   2019-02-10 [1] RSPM (R 4.0.0)
    #>  testthat        3.0.0   2020-10-31 [1] RSPM (R 4.0.3)
    #>  texreg          1.37.5  2020-06-18 [1] RSPM (R 4.0.1)
    #>  usethis         1.6.3   2020-09-17 [1] RSPM (R 4.0.2)
    #>  withr           2.3.0   2020-09-22 [1] RSPM (R 4.0.2)
    #>  xfun            0.19    2020-10-30 [1] RSPM (R 4.0.3)
    #>  yaml            2.2.1   2020-02-01 [1] RSPM (R 4.0.0)
    #> 
    #> [1] /usr/local/lib/R/site-library
    #> [2] /usr/lib/R/site-library
    #> [3] /usr/lib/R/library

</details>

After poking around a bit, I think the problem could be that calls to DeclareDesigns custom `future_lapply()` use `future.seed = NA`. Changing it to `TRUE` seems to fix reproducibility, but admittedly, I don't know if this has any other ramifications.

**Comment by nfultz** [comment]
There's some discussion around this here - https://www.jottr.org/2020/09/22/push-for-statical-sound-rng/

I agree that this is probably coming from some old logic from 2017 to fall back to regular lapply if future is not installed:
https://github.com/DeclareDesign/DeclareDesign/blob/master/R/utilities.R#L62-L68

Also note that in https://rdrr.io/cran/future.apply/man/future_lapply.html it says

> If future.seed = NA, a L'Ecuyer-CMRG RNG seed is randomly created.

So if that isn't true we should update the defaults accordingly.

EDI: Also IIRC reproducibility only works within plans and not between them, although it may have been fixed.

EDI2:

Based on

```
require(future.apply)

plan("sequential")
set.seed(999)
future_lapply(seq(3), rnorm, n = 1, future.seed = NA)
set.seed(999)
future_lapply(seq(3), rnorm, n = 1, future.seed = NA)

plan("multicore")
set.seed(999)
future_lapply(seq(3), rnorm, n = 1, future.seed = NA)
set.seed(999)
future_lapply(seq(3), rnorm, n = 1, future.seed = NA)

```

It seems like NA is the correct way to force future_lapply to seed the  L'Ecuyer-CMRG RNG always - I think this issue might be trickier to actually pin down.

**Comment by HenrikBengtsson** [comment]
Author of future here: You wanna use `future.seed = TRUE` if your `future_lapply()` iterations make use of the RNG - it'll use a parallel RNG seed based on the current random seed.  If you know it does not use the RNG, use `future.seed = FALSE` (and the future framework will produce a big warning if it detects the RNG was still used somewhere in the stack).  

I'll see if I can clarify the docs for when `future.seed = NA` should be used, but basically don't use it here.
