### ISSUE TITLE
Type-s error is a conditional, not a joint, probability

### ISSUE THREAD

**Issue by jaspercooper** [DeclareDesign/DeclareDesign#45]
We currently say that a type-S error for a design is given by:
```r
type_s_rate = mean((sign(est) != sign(estimand)) & p < .05)
```
In other words, that it is the joint probability a simulated estimate being: significant (**A**) and in  the wrong direction (**B**). We've gone back and forth on this a bit but I'm pretty sure now that we want a conditional probability: among the estimates that are significant, what is the probability they have the wrong sign (Pr(B | A))?

Gelman and Carlin's [original paper](http://journals.sagepub.com/doi/pdf/10.1177/1745691614551642) defines the type-S error rate as: 
> the probability that the replicated estimate has the incorrect sign, if it is statistically significantly different from zero, 

which sure sounds conditional to me. 

They provide the following code: 
```r
z <- qt(1-alpha/2, df)
p.hi <- 1 - pt(z-A/s, df)
p.lo <- pt(-z-A/s, df)
power <- p.hi + p.lo
typeS <- p.lo/power
```
`p.hi` here is the probability that the estimate is significant and correctly signed (i.e. Pr(A and not B)). `p.lo` is the probability that the estimate is significant and incorrectly signed (i.e. Pr(A and B)). Power is the probability that any estimate is significant irrespective of sign, i.e. Pr(A) = Pr(A and not B) + Pr(A and B),   p.hi + p.lo. So in the code above, typeS is equal to Pr(A and B) / Pr(A) which is none other than Pr(B | A), i.e. the probability of being wrongly signed, given that an effect is significant. 

Conclusion: to be consistent with the code and text of Gelman and Carlin we should have 
```r
type_s_rate = mean((sign(est) != sign(estimand))[ p < .05] )
```
Happy to implement or let someone else take it from here.

**Comment by graemeblair** [comment]
Thanks, Jasper, this is a change in `diagnose_design` where it currently creates diagnosands.
