### ISSUE TITLE
estimands should be a function of other estimands

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/DeclareDesign#454]
```
mands <- declare_population(N = 5) + declare_estimands(estimand1 = rnorm(1), estimand2 = 5*estimand1)
draw_estimands(mands)
Error: Error in step 2 (estimand):
	Error in eval_tidy(options[[i]], data = data): object 'estimand1' not found
```

In fabricate(), later objects can be a function of earlier variables, seems like this should be possible here too. Applications include ratio of estimands.

**Comment by nfultz** [comment]
This would require modifying the overscoping in the default estimand handler - https://github.com/DeclareDesign/DeclareDesign/blob/6271555ec116f12e012025df1e145fa7e049015e/R/declare_estimand.R#L196-L199 . This seems very doable for functions of estimands within a step, and extremely difficult for functions of estimands that are declared in different steps.
