### ISSUE TITLE
Annoying opaque white rectangle on every page of book

### ISSUE THREAD

**Issue by grasshoppermouse** [DeclareDesign/DeclareDesign#476]
There is an annoying opaque white rectangle in the center of every page of the book:

https://book.declaredesign.org/

<img width="703" alt="Screen Shot 2021-08-23 at 9 56 56 AM" src="https://user-images.githubusercontent.com/7534138/130487403-6648e714-733e-429e-82c4-939ba8a781b2.png">

**Comment by nfultz** [comment]
This might be a bad interaction between the generated pages and your browser. Can you share the version information about your OS and browser?

Also if you have the ability, can you pop into the developer tools / DOM inspector , click on the white box, and let us know which element it is exactly?

**Comment by grasshoppermouse** [comment]
MacOS 10.14.6
Safari: 14.1.2 
Chrome (see it here too): 92.0.4515.131

DOM: I think it's zoomImg

<img width="587" alt="Screen Shot 2021-08-23 at 11 00 25 AM" src="https://user-images.githubusercontent.com/7534138/130494782-aaeaad67-9833-4a95-895e-ba7336554b66.png">

**Comment by nfultz** [comment]
Very strange - I think that's the plugin that lets you click on an image to zoom in on it?
EDIT
Possible https://stackoverflow.com/questions/40401680/how-to-zoom-in-on-plots-inside-an-rmarkdown-presentation

**Comment by grasshoppermouse** [comment]
Not sure. It floats (i.e., stays centered on screen as you scroll). Clicking it doesn't do anything.

**Comment by graemeblair** [comment]
Thanks @grasshoppermouse for your report and @nfultz for tracking down. This should be fixed now, @grasshoppermouse would you kindly confirm?

**Comment by grasshoppermouse** [comment]
Seems to be fixed. Thanks!
