### ISSUE TITLE
RFC - Refactor citations to flow through pipeline 

### ISSUE THREAD

**Issue by nfultz** [DeclareDesign/DeclareDesign#48]
Currently, we save design metadata (citation, etc) by named arguments to the `declare_design` main function.  Roughly half of the attributes on the Design object are for these fields, and they are accessed in an ad-hoc basis or through summary.

Instead, we could move this functionality in to it's own declaration. Maybe it could look like this:

```
declare_design(
  declare_metadata(author="Neal", title="Is Awesome"),
  declare_population(countries=level(N=50)),
  ...
)
```

I think this would improve the function's focus and let us separate out some concerns. It would also let us propagate metadata to diagnosis/samples made using the design functions, which could be useful for reproducibility and debugging, eg by attaching version numbers, R session info, git refs, RNG seeds, etc .  

You could also imagine having multiple sets of metadata, such as

```
declare_design(
  reference_design_from_library$design_function,
  declare_metadata(author="Neal", title="Is Awesome"),
  declare_potential_outcome(HIA=1, RYLAH=2),
  ...
)
```
which would carry metadata from the reference design, add my own tags, and continue.

**Comment by graemeblair** [comment]
good idea. assume we'd replace if you provide a tag that already exists
