### ISSUE TITLE
Has anyone scripted repeated measures Anova?

### ISSUE THREAD

**Issue by oscci** [DeclareDesign/DeclareDesign#492]
I'm using DeclareDesign to compare how different researchers managed to come to diametrically different conclusions regarding effectiveness of an intervention, using the same dataset. It's worked well in demonstrating that one set of researchers created bias in the results by selecting on a post-intervention variable. Not surprising to those who know this stuff, but nice to be able to show it. For completeness, I'd like to also model the exact analysis they did, which was to use 2-way mixed ANOVA, with time as a repeated measure and group as between subjects, rather than having pretest as covariate.  I'm nearly there: I'm just wondering if anyone has already scripted this.  I realise Anova is a bit of an aberration that isn't used in many fields other than psychology, so perhaps it is not a priority.  I have got an analysis in lme that is equivalent but it is fiddly, and requires reshaping the data to long form. Happy to share what I've done so far ,but wondered if I am reinventing the wheel here.

**Comment by macartan** [comment]
I don't think I have seen code for exactly this

there's a two way fixed effects design here
https://book.declaredesign.org/library/observational-causal.html#def-ch16num3
and you can use it to show how people might conceptualize the inquiry
differently

Figure 18.10
https://book.declaredesign.org/library/experimental-causal.html#sec-ch18s6
shows an example of "per protocol" analysis which is a type of post
treatment conditioning

**Comment by oscci** [comment]
Many thanks. I'll add my code here, just in case it is useful. Let me know if you spot any problems. This isn't a design I'd encourage anyone to use in this context, but it's good to be able to evaluate it. The starting point is the main pretest_posttest design. Then modified to include:
#convert to long form
reshaper <- 
  function(data){
    data |> 
      gather(key = "time", value = "score", Y_t1, Y_t2) |> 
      convert_as_factor(ID, time)
  }
myreshape <- declare_assignment(handler=reshaper)

and then use lme to get analysis equivalent to a 2 x 2 mixed anova, thus:
# now run lme (incorporating exclusions specific to this case)
anova2way <- declare_estimator(score ~ Z * time, random=~time|ID, 
                               .method = lme, 
                               .summary=tidy,
                                term = "Z:timeY_t2",
                                inquiry = "EffSize",
                                subset = (HasData == 1 & Exclude==FALSE), 
                                label = "Interaction: mixed anova")

mydesign <- population+ potential_outcomes + 
  estimand+ assignment + reveal_t2 + report + myreshape + 
  anova2way
