### ISSUE TITLE
drop = FALSE issues in diagnose_design

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/DeclareDesign#53]
When running diagnose_design with a single estimand, you get this:

Error in apply(df[, !colnames(df) %in% group_by_set], 2, sd) : 
  dim(X) must have a positive length

We need to do a package-wide search for drop = FALSE issues like this.

**Comment by graemeblair** [comment]
That line doesn't appear in `diagnose_design` anymore and can't exactly reproduce this. @lukesonnet saw you mentioned this in another PR, do you or @nfultz know if this is still relevant?

**Comment by nfultz** [comment]
Not possible anymore, the SEs are calculated via nested lapply now.
