### ISSUE TITLE
install.packages() does not work for R 3.3.0

### ISSUE THREAD

**Issue by gerasy1987** [DeclareDesign/DeclareDesign#7]
`Warning in install.packages: package ‘http://declaredesign.org/latest.tar.gz’ is not available (for R version 3.3.0)`

**Comment by graemeblair** [comment]
Thanks! This appears to be RStudio, specific. The fix is:

install.packages("http://declaredesign.org/latest.tar.gz", repos = NULL)

Try that out and if it doesn't work work please reopen this issue. I have updated the Web site to reflect this change.
