### ISSUE TITLE
shorter potential outcome names

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/DeclareDesign#85]
Do we need Y_Z_0 to have all three underscores for parsing, or is there a way to shorten these to for example Y_Z0 and still easily parse. In general, is there a better way with these names when you start to have multiple treatments and get into ridiculous things like Y_Z11_Z21 etc.

**Comment by lukesonnet** [comment]
Since names can't be numbers (unless back ticked....) I think the solution of Y_Z1 is fine and we just warn/error if people use numbers as names.

**Comment by graemeblair** [comment]
I still find `Y_Z11_Z21` pretty hard to interpret, but don't have an alternative in mind.
