### ISSUE TITLE
option to add all probs of assignment, not just condition probs

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/DeclareDesign#87]
Sometimes you need the other condition probs with complex assignment designs, seems like we could easily add this, i.e. it adds not just Z_cond_prob, but Z_cond_prob_1, Z_cond_prob_0, etc. Thoughts? We'd need to (unless I'm missing something) add a second helper function in randomizr like `obtain_condition_probabilities` that would return the full prob mat given a declaration (right now, there are block_ra_probabilities etc. for each design that can return the full prob mat, but not a function that can take a declaration).

**Comment by nfultz** [comment]
Does randomizr provide these??

**Comment by graemeblair** [comment]
@acoppock it looks like we need `obtain_probabilities_matrix` to implement this, there is no function that takes an RA declaration and returns a matrix of probabilities where columns are conditions. is that right?

**Comment by nfultz** [comment]
This is now lazily generated by

```r
declaration$probabilities_matrix
```

This however feels like a good use case for the nested data PR for fabricatr.

**Comment by graemeblair** [comment]
Implement in `declare_assignment` as option `append_probabilities_matrix` defaults to `FALSE`
