### ISSUE TITLE
remove error in potential_outcomes_function_discrete?

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/DeclareDesign#9]
If you make multiple POs using the variable-by-variable way of doing things with different prefixes, i.e. Y_Z_0, Y_Z_1, Y2_Z_0, Y_2_Z_1 it will scream i.e.:

```
> pop() %>% pos
Error in DeclareDesign:::potential_outcomes_function_discrete(conflict_latent_Z_0 = -2 +  : 
  All of the variable names you create should begin with the same prefix, i.e. Y_Z_
```

For latent variables where you may want to create Y_latent_Z_0 as well as Y_binary_Z_0 this seems like annoying behavior; you have to create two different PO declarations.

Suggest we remove this error?

**Comment by jaspercooper** [comment]
+1
