### ISSUE TITLE
easy programming tools for repeated similar declarations

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/DeclareDesign#90]
When you have a design with many outcomes and many estimators assigned to them that are identical but for the outcome, should add tools to duplicate the estimators / estimands / ... ?

i.e. 

declare_estimators_multiple(base = my_estimator, other_outcomes = c(y2, y3, y4))

I suspect there are other kinds of things that will be repeated and we should have tools so people don't have to use lapply / sapply and run into horrible NSE errors.

Perhaps there is a way to use !! or !!! rlang operators?

**Comment by lukesonnet** [comment]
It automatically does this if you list all of the estimators in your design declaration?

`declare_design(pop, pos, revealys, estimand1, estimand2, estimator1, estimator2)`

**Comment by nfultz** [comment]
The way lm does this is 

```
> lm(cbind(mpg, hp)~cyl+disp, mtcars)

Call:
lm(formula = cbind(mpg, hp) ~ cyl + disp, data = mtcars)

Coefficients:
             mpg           hp          
(Intercept)   34.66099474  -32.43168548
cyl           -1.58727681   24.51452142
disp          -0.02058363    0.11891193
```

This only constructs and factors the RHS once for multiple outcome variables - more outcomes are essentially computationally free - we should add this functionality to estimatr, and expose it in DD.

**Comment by nfultz** [comment]
Luke has added multiple outcomes to estimatr - other models may need a custom handler.
