### ISSUE TITLE
syntactic sugar for multi-outcome / multi estimator situations

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/DeclareDesign#92]
Perhaps we could do this:

```
my_outcomes <- c("y1", "y2")
declare_reveal(outcome_variable_names = !! my_outcomes)
```

where the result would be revealing both

**Comment by nfultz** [comment]
works!

**Comment by graemeblair** [comment]
I'm reopening to pin remembering to discuss doing this for declare_estimator, i.e.

```
outcomes <- c("Y1", "Y2")
declare_estimator(!!outcome ~ Z)
```

**Comment by graemeblair** [comment]
in meeting, we decided that we will (a) allow this for `lm_robust`; (b) not implement by default besides that in the estimator handler; and (c) write a multi-outcome handler in the future that allows multiple outcomes and implements multiple testing corrections.
