### ISSUE TITLE
ri2 handler

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/DeclareDesign#98]
Once we have things finalized with the easier-to-use handler-model syntax in declare_estimator, suggest we build additional built-in handler:
- estimator + RI -- where it runs RI using `ri2` and adds the RI p-value to the estimates df. Obv requires an easy way to send the RA declaration. **v1 release**

**Comment by nfultz** [comment]
I think that this should go in the ri package - it can "Enhances: DeclareDesign"

**Comment by acoppock** [comment]
At a minimum, ri2 needs a tidier: https://github.com/acoppock/ri2/issues/18, which will greatly increase interoperability with DD
