### ISSUE TITLE
JASPER: is there a way to break a loop and have a function return the progress it made?

### ISSUE THREAD

**Issue by acoppock** [DeclareDesign/DeclareDesign#99]

**Comment by jaspercooper** [comment]
Turns out the answer is yes, using the `<<-` operator!  

You need to set it up in quite a tricky way and I fear it could slow down the *ply function. It also requires creating the object in the environment first (i.e. below you have to create `saved_output` first). 

```r
saved_output <- list()
replicate(
  n = 1000000000,
  expr = {
    something <- sample(1:100)
    saved_output <<- c(saved_output,something)
  }
)
```

[This is where I gleaned the info](http://stackoverflow.com/questions/33933714/save-output-from-interrupted-loop-ply)

**Comment by acoppock** [comment]
I believe that diagnose is building a list — if we stop diagnose early, how do we get the list so far?

**Comment by jaspercooper** [comment]
Here's how you would do it: 

```r
a_function <- function(){
  assign(x = "saved_output",envir = globalenv(),value = list())
replicate(
  n = 1000000000,
  expr = {
    something <- sample(1:100)
    saved_output <<- c(saved_output,something)
  }
)
}

design_list <- a_function()
```
In other words, assign an empty object to the global environment, and then include in the loop / apply environment a `<<-` operator (I THINK).

**Comment by acoppock** [comment]
Ok, ok, i get it, we’d have to essentially write to the global environment, then use the <<- operator to write up an environment.

Interesting — probably not the right thing to do in this case, but good to know!

**Comment by jaspercooper** [comment]
You'd want the `<<-` somewhere around [here](https://github.com/DeclareDesign/DeclareDesign/blob/master/R/diagnose_design.R#L120). If we rewrote diagnose_design() to bind rows as it goes then we could simply throw the simulations dataframe into the user's global environment. Pending such a big rewrite we could at least give them their estimates list and maybe a handy function for turning it into a simulations dataframe (i.e. it just does all the bits of diagnose_design that come after the loop). 

I agree it may not be the right way to go here. I'll definitely be using it for simulations though.
